//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Lcapas.Core.quesvc {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="APASQueueService", Namespace="http://APASProxy.ServiceContracts/2007/04")]
    public partial class APASQueueService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetSentTransferRequestsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSentTranscriptsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetReceivedTranscriptsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetReceivedTransferRequestsOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendTrancriptOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendTransferRequestOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendApplicationOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetHostInstitutionOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDecompressedDecodedMessageOperationCompleted;
        
        private System.Threading.SendOrPostCallback PrepareCompressedEncodedMessageOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetReceivedApplicationsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSentApplicationsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRegisteredEducationalInstitutionsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetReceivedErrorsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public APASQueueService() {
            this.Url = global::Lcapas.Core.Properties.Settings.Default.LcapasCore_quesvc_APASQueueService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetSentTransferRequestsCompletedEventHandler GetSentTransferRequestsCompleted;
        
        /// <remarks/>
        public event GetSentTranscriptsCompletedEventHandler GetSentTranscriptsCompleted;
        
        /// <remarks/>
        public event GetReceivedTranscriptsCompletedEventHandler GetReceivedTranscriptsCompleted;
        
        /// <remarks/>
        public event GetReceivedTransferRequestsCompletedEventHandler GetReceivedTransferRequestsCompleted;
        
        /// <remarks/>
        public event SendTrancriptCompletedEventHandler SendTrancriptCompleted;
        
        /// <remarks/>
        public event SendTransferRequestCompletedEventHandler SendTransferRequestCompleted;
        
        /// <remarks/>
        public event SendApplicationCompletedEventHandler SendApplicationCompleted;
        
        /// <remarks/>
        public event GetHostInstitutionCompletedEventHandler GetHostInstitutionCompleted;
        
        /// <remarks/>
        public event GetDecompressedDecodedMessageCompletedEventHandler GetDecompressedDecodedMessageCompleted;
        
        /// <remarks/>
        public event PrepareCompressedEncodedMessageCompletedEventHandler PrepareCompressedEncodedMessageCompleted;
        
        /// <remarks/>
        public event GetReceivedApplicationsCompletedEventHandler GetReceivedApplicationsCompleted;
        
        /// <remarks/>
        public event GetSentApplicationsCompletedEventHandler GetSentApplicationsCompleted;
        
        /// <remarks/>
        public event GetRegisteredEducationalInstitutionsCompletedEventHandler GetRegisteredEducationalInstitutionsCompleted;
        
        /// <remarks/>
        public event GetReceivedErrorsCompletedEventHandler GetReceivedErrorsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://APASProxy.ServiceContracts/2007/04/GetSentTransferRequests", RequestNamespace="http://APASProxy.ServiceContracts/2007/04", ResponseNamespace="http://APASProxy.ServiceContracts/2007/04", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SentTransferRequest[] GetSentTransferRequests([System.Xml.Serialization.XmlElementAttribute(Namespace="http://APASProxy.DataTypes/2007/04")] SentTransferRequestsFilter sentTransferRequestsFilter) {
            object[] results = this.Invoke("GetSentTransferRequests", new object[] {
                        sentTransferRequestsFilter});
            return ((SentTransferRequest[])(results[0]));
        }
        
        /// <remarks/>
        public void GetSentTransferRequestsAsync(SentTransferRequestsFilter sentTransferRequestsFilter) {
            this.GetSentTransferRequestsAsync(sentTransferRequestsFilter, null);
        }
        
        /// <remarks/>
        public void GetSentTransferRequestsAsync(SentTransferRequestsFilter sentTransferRequestsFilter, object userState) {
            if ((this.GetSentTransferRequestsOperationCompleted == null)) {
                this.GetSentTransferRequestsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSentTransferRequestsOperationCompleted);
            }
            this.InvokeAsync("GetSentTransferRequests", new object[] {
                        sentTransferRequestsFilter}, this.GetSentTransferRequestsOperationCompleted, userState);
        }
        
        private void OnGetSentTransferRequestsOperationCompleted(object arg) {
            if ((this.GetSentTransferRequestsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSentTransferRequestsCompleted(this, new GetSentTransferRequestsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://APASProxy.ServiceContracts/2007/04/GetSentTranscripts", RequestNamespace="http://APASProxy.ServiceContracts/2007/04", ResponseNamespace="http://APASProxy.ServiceContracts/2007/04", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SentTranscript[] GetSentTranscripts([System.Xml.Serialization.XmlElementAttribute(Namespace="http://APASProxy.DataTypes/2007/04")] SentTranscriptsFilter sentTranscriptsFilter) {
            object[] results = this.Invoke("GetSentTranscripts", new object[] {
                        sentTranscriptsFilter});
            return ((SentTranscript[])(results[0]));
        }
        
        /// <remarks/>
        public void GetSentTranscriptsAsync(SentTranscriptsFilter sentTranscriptsFilter) {
            this.GetSentTranscriptsAsync(sentTranscriptsFilter, null);
        }
        
        /// <remarks/>
        public void GetSentTranscriptsAsync(SentTranscriptsFilter sentTranscriptsFilter, object userState) {
            if ((this.GetSentTranscriptsOperationCompleted == null)) {
                this.GetSentTranscriptsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSentTranscriptsOperationCompleted);
            }
            this.InvokeAsync("GetSentTranscripts", new object[] {
                        sentTranscriptsFilter}, this.GetSentTranscriptsOperationCompleted, userState);
        }
        
        private void OnGetSentTranscriptsOperationCompleted(object arg) {
            if ((this.GetSentTranscriptsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSentTranscriptsCompleted(this, new GetSentTranscriptsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://APASProxy.ServiceContracts/2007/04/GetReceivedTranscripts", RequestNamespace="http://APASProxy.ServiceContracts/2007/04", ResponseNamespace="http://APASProxy.ServiceContracts/2007/04", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ReceivedTranscript[] GetReceivedTranscripts([System.Xml.Serialization.XmlElementAttribute(Namespace="http://APASProxy.DataTypes/2007/04")] ReceivedTranscriptsFilter receivedTranscriptsFilter) {
            object[] results = this.Invoke("GetReceivedTranscripts", new object[] {
                        receivedTranscriptsFilter});
            return ((ReceivedTranscript[])(results[0]));
        }
        
        /// <remarks/>
        public void GetReceivedTranscriptsAsync(ReceivedTranscriptsFilter receivedTranscriptsFilter) {
            this.GetReceivedTranscriptsAsync(receivedTranscriptsFilter, null);
        }
        
        /// <remarks/>
        public void GetReceivedTranscriptsAsync(ReceivedTranscriptsFilter receivedTranscriptsFilter, object userState) {
            if ((this.GetReceivedTranscriptsOperationCompleted == null)) {
                this.GetReceivedTranscriptsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetReceivedTranscriptsOperationCompleted);
            }
            this.InvokeAsync("GetReceivedTranscripts", new object[] {
                        receivedTranscriptsFilter}, this.GetReceivedTranscriptsOperationCompleted, userState);
        }
        
        private void OnGetReceivedTranscriptsOperationCompleted(object arg) {
            if ((this.GetReceivedTranscriptsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetReceivedTranscriptsCompleted(this, new GetReceivedTranscriptsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://APASProxy.ServiceContracts/2007/04/GetReceivedTransferRequests", RequestNamespace="http://APASProxy.ServiceContracts/2007/04", ResponseNamespace="http://APASProxy.ServiceContracts/2007/04", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ReceivedTransferRequest[] GetReceivedTransferRequests([System.Xml.Serialization.XmlElementAttribute(Namespace="http://APASProxy.DataTypes/2007/04")] ReceivedTransferRequestsFilter receivedTransferRequestsFilter) {
            object[] results = this.Invoke("GetReceivedTransferRequests", new object[] {
                        receivedTransferRequestsFilter});
            return ((ReceivedTransferRequest[])(results[0]));
        }
        
        /// <remarks/>
        public void GetReceivedTransferRequestsAsync(ReceivedTransferRequestsFilter receivedTransferRequestsFilter) {
            this.GetReceivedTransferRequestsAsync(receivedTransferRequestsFilter, null);
        }
        
        /// <remarks/>
        public void GetReceivedTransferRequestsAsync(ReceivedTransferRequestsFilter receivedTransferRequestsFilter, object userState) {
            if ((this.GetReceivedTransferRequestsOperationCompleted == null)) {
                this.GetReceivedTransferRequestsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetReceivedTransferRequestsOperationCompleted);
            }
            this.InvokeAsync("GetReceivedTransferRequests", new object[] {
                        receivedTransferRequestsFilter}, this.GetReceivedTransferRequestsOperationCompleted, userState);
        }
        
        private void OnGetReceivedTransferRequestsOperationCompleted(object arg) {
            if ((this.GetReceivedTransferRequestsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetReceivedTransferRequestsCompleted(this, new GetReceivedTransferRequestsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://APASProxy.ServiceContracts/2007/04/SendTrancript", RequestNamespace="http://APASProxy.ServiceContracts/2007/04", ResponseNamespace="http://APASProxy.ServiceContracts/2007/04", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(Namespace="http://APASProxy.DataTypes/2007/04")]
        public Acknowledgment SendTrancript([System.Xml.Serialization.XmlElementAttribute(Namespace="http://APASProxy.DataTypes/2007/04")] SentTranscript transcriptToSend) {
            object[] results = this.Invoke("SendTrancript", new object[] {
                        transcriptToSend});
            return ((Acknowledgment)(results[0]));
        }
        
        /// <remarks/>
        public void SendTrancriptAsync(SentTranscript transcriptToSend) {
            this.SendTrancriptAsync(transcriptToSend, null);
        }
        
        /// <remarks/>
        public void SendTrancriptAsync(SentTranscript transcriptToSend, object userState) {
            if ((this.SendTrancriptOperationCompleted == null)) {
                this.SendTrancriptOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendTrancriptOperationCompleted);
            }
            this.InvokeAsync("SendTrancript", new object[] {
                        transcriptToSend}, this.SendTrancriptOperationCompleted, userState);
        }
        
        private void OnSendTrancriptOperationCompleted(object arg) {
            if ((this.SendTrancriptCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendTrancriptCompleted(this, new SendTrancriptCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://APASProxy.ServiceContracts/2007/04/SendTransferRequest", RequestNamespace="http://APASProxy.ServiceContracts/2007/04", ResponseNamespace="http://APASProxy.ServiceContracts/2007/04", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(Namespace="http://APASProxy.DataTypes/2007/04")]
        public Acknowledgment SendTransferRequest([System.Xml.Serialization.XmlElementAttribute(Namespace="http://APASProxy.DataTypes/2007/04")] SentTransferRequest transferRequestToSend) {
            object[] results = this.Invoke("SendTransferRequest", new object[] {
                        transferRequestToSend});
            return ((Acknowledgment)(results[0]));
        }
        
        /// <remarks/>
        public void SendTransferRequestAsync(SentTransferRequest transferRequestToSend) {
            this.SendTransferRequestAsync(transferRequestToSend, null);
        }
        
        /// <remarks/>
        public void SendTransferRequestAsync(SentTransferRequest transferRequestToSend, object userState) {
            if ((this.SendTransferRequestOperationCompleted == null)) {
                this.SendTransferRequestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendTransferRequestOperationCompleted);
            }
            this.InvokeAsync("SendTransferRequest", new object[] {
                        transferRequestToSend}, this.SendTransferRequestOperationCompleted, userState);
        }
        
        private void OnSendTransferRequestOperationCompleted(object arg) {
            if ((this.SendTransferRequestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendTransferRequestCompleted(this, new SendTransferRequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://APASProxy.ServiceContracts/2007/04/SendApplication", RequestNamespace="http://APASProxy.ServiceContracts/2007/04", ResponseNamespace="http://APASProxy.ServiceContracts/2007/04", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(Namespace="http://APASProxy.DataTypes/2007/04")]
        public Acknowledgment SendApplication([System.Xml.Serialization.XmlElementAttribute(Namespace="http://APASProxy.DataTypes/2007/04")] SentApplication applicationToSend) {
            object[] results = this.Invoke("SendApplication", new object[] {
                        applicationToSend});
            return ((Acknowledgment)(results[0]));
        }
        
        /// <remarks/>
        public void SendApplicationAsync(SentApplication applicationToSend) {
            this.SendApplicationAsync(applicationToSend, null);
        }
        
        /// <remarks/>
        public void SendApplicationAsync(SentApplication applicationToSend, object userState) {
            if ((this.SendApplicationOperationCompleted == null)) {
                this.SendApplicationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendApplicationOperationCompleted);
            }
            this.InvokeAsync("SendApplication", new object[] {
                        applicationToSend}, this.SendApplicationOperationCompleted, userState);
        }
        
        private void OnSendApplicationOperationCompleted(object arg) {
            if ((this.SendApplicationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendApplicationCompleted(this, new SendApplicationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://APASProxy.ServiceContracts/2007/04/GetHostInstitution", RequestNamespace="http://APASProxy.ServiceContracts/2007/04", ResponseNamespace="http://APASProxy.ServiceContracts/2007/04", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(Namespace="http://APASProxy.DataTypes/2007/04")]
        public RegisteredEducationalInstitution GetHostInstitution() {
            object[] results = this.Invoke("GetHostInstitution", new object[0]);
            return ((RegisteredEducationalInstitution)(results[0]));
        }
        
        /// <remarks/>
        public void GetHostInstitutionAsync() {
            this.GetHostInstitutionAsync(null);
        }
        
        /// <remarks/>
        public void GetHostInstitutionAsync(object userState) {
            if ((this.GetHostInstitutionOperationCompleted == null)) {
                this.GetHostInstitutionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetHostInstitutionOperationCompleted);
            }
            this.InvokeAsync("GetHostInstitution", new object[0], this.GetHostInstitutionOperationCompleted, userState);
        }
        
        private void OnGetHostInstitutionOperationCompleted(object arg) {
            if ((this.GetHostInstitutionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetHostInstitutionCompleted(this, new GetHostInstitutionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://APASProxy.ServiceContracts/2007/04/GetDecompressedDecodedMessage", RequestNamespace="http://APASProxy.ServiceContracts/2007/04", ResponseNamespace="http://APASProxy.ServiceContracts/2007/04", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetDecompressedDecodedMessage(string message) {
            object[] results = this.Invoke("GetDecompressedDecodedMessage", new object[] {
                        message});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetDecompressedDecodedMessageAsync(string message) {
            this.GetDecompressedDecodedMessageAsync(message, null);
        }
        
        /// <remarks/>
        public void GetDecompressedDecodedMessageAsync(string message, object userState) {
            if ((this.GetDecompressedDecodedMessageOperationCompleted == null)) {
                this.GetDecompressedDecodedMessageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDecompressedDecodedMessageOperationCompleted);
            }
            this.InvokeAsync("GetDecompressedDecodedMessage", new object[] {
                        message}, this.GetDecompressedDecodedMessageOperationCompleted, userState);
        }
        
        private void OnGetDecompressedDecodedMessageOperationCompleted(object arg) {
            if ((this.GetDecompressedDecodedMessageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDecompressedDecodedMessageCompleted(this, new GetDecompressedDecodedMessageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://APASProxy.ServiceContracts/2007/04/PrepareCompressedEncodedMessage", RequestNamespace="http://APASProxy.ServiceContracts/2007/04", ResponseNamespace="http://APASProxy.ServiceContracts/2007/04", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string PrepareCompressedEncodedMessage(string message) {
            object[] results = this.Invoke("PrepareCompressedEncodedMessage", new object[] {
                        message});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PrepareCompressedEncodedMessageAsync(string message) {
            this.PrepareCompressedEncodedMessageAsync(message, null);
        }
        
        /// <remarks/>
        public void PrepareCompressedEncodedMessageAsync(string message, object userState) {
            if ((this.PrepareCompressedEncodedMessageOperationCompleted == null)) {
                this.PrepareCompressedEncodedMessageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPrepareCompressedEncodedMessageOperationCompleted);
            }
            this.InvokeAsync("PrepareCompressedEncodedMessage", new object[] {
                        message}, this.PrepareCompressedEncodedMessageOperationCompleted, userState);
        }
        
        private void OnPrepareCompressedEncodedMessageOperationCompleted(object arg) {
            if ((this.PrepareCompressedEncodedMessageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PrepareCompressedEncodedMessageCompleted(this, new PrepareCompressedEncodedMessageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://APASProxy.ServiceContracts/2007/04/GetReceivedApplications", RequestNamespace="http://APASProxy.ServiceContracts/2007/04", ResponseNamespace="http://APASProxy.ServiceContracts/2007/04", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ReceivedApplication[] GetReceivedApplications([System.Xml.Serialization.XmlElementAttribute(Namespace="http://APASProxy.DataTypes/2007/04")] ReceivedApplicationsFilter receivedApplicationsFilter) {
            object[] results = this.Invoke("GetReceivedApplications", new object[] {
                        receivedApplicationsFilter});
            return ((ReceivedApplication[])(results[0]));
        }
        
        /// <remarks/>
        public void GetReceivedApplicationsAsync(ReceivedApplicationsFilter receivedApplicationsFilter) {
            this.GetReceivedApplicationsAsync(receivedApplicationsFilter, null);
        }
        
        /// <remarks/>
        public void GetReceivedApplicationsAsync(ReceivedApplicationsFilter receivedApplicationsFilter, object userState) {
            if ((this.GetReceivedApplicationsOperationCompleted == null)) {
                this.GetReceivedApplicationsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetReceivedApplicationsOperationCompleted);
            }
            this.InvokeAsync("GetReceivedApplications", new object[] {
                        receivedApplicationsFilter}, this.GetReceivedApplicationsOperationCompleted, userState);
        }
        
        private void OnGetReceivedApplicationsOperationCompleted(object arg) {
            if ((this.GetReceivedApplicationsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetReceivedApplicationsCompleted(this, new GetReceivedApplicationsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://APASProxy.ServiceContracts/2007/04/GetSentApplications", RequestNamespace="http://APASProxy.ServiceContracts/2007/04", ResponseNamespace="http://APASProxy.ServiceContracts/2007/04", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SentApplication[] GetSentApplications([System.Xml.Serialization.XmlElementAttribute(Namespace="http://APASProxy.DataTypes/2007/04")] SentApplicationsFilter sentApplicationsFilter) {
            object[] results = this.Invoke("GetSentApplications", new object[] {
                        sentApplicationsFilter});
            return ((SentApplication[])(results[0]));
        }
        
        /// <remarks/>
        public void GetSentApplicationsAsync(SentApplicationsFilter sentApplicationsFilter) {
            this.GetSentApplicationsAsync(sentApplicationsFilter, null);
        }
        
        /// <remarks/>
        public void GetSentApplicationsAsync(SentApplicationsFilter sentApplicationsFilter, object userState) {
            if ((this.GetSentApplicationsOperationCompleted == null)) {
                this.GetSentApplicationsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSentApplicationsOperationCompleted);
            }
            this.InvokeAsync("GetSentApplications", new object[] {
                        sentApplicationsFilter}, this.GetSentApplicationsOperationCompleted, userState);
        }
        
        private void OnGetSentApplicationsOperationCompleted(object arg) {
            if ((this.GetSentApplicationsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSentApplicationsCompleted(this, new GetSentApplicationsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://APASProxy.ServiceContracts/2007/04/GetRegisteredEducationalInstitutions", RequestNamespace="http://APASProxy.ServiceContracts/2007/04", ResponseNamespace="http://APASProxy.ServiceContracts/2007/04", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RegisteredEducationalInstitution[] GetRegisteredEducationalInstitutions() {
            object[] results = this.Invoke("GetRegisteredEducationalInstitutions", new object[0]);
            return ((RegisteredEducationalInstitution[])(results[0]));
        }
        
        /// <remarks/>
        public void GetRegisteredEducationalInstitutionsAsync() {
            this.GetRegisteredEducationalInstitutionsAsync(null);
        }
        
        /// <remarks/>
        public void GetRegisteredEducationalInstitutionsAsync(object userState) {
            if ((this.GetRegisteredEducationalInstitutionsOperationCompleted == null)) {
                this.GetRegisteredEducationalInstitutionsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRegisteredEducationalInstitutionsOperationCompleted);
            }
            this.InvokeAsync("GetRegisteredEducationalInstitutions", new object[0], this.GetRegisteredEducationalInstitutionsOperationCompleted, userState);
        }
        
        private void OnGetRegisteredEducationalInstitutionsOperationCompleted(object arg) {
            if ((this.GetRegisteredEducationalInstitutionsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRegisteredEducationalInstitutionsCompleted(this, new GetRegisteredEducationalInstitutionsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://APASProxy.ServiceContracts/2007/04/GetReceivedErrors", RequestNamespace="http://APASProxy.ServiceContracts/2007/04", ResponseNamespace="http://APASProxy.ServiceContracts/2007/04", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ReceivedError[] GetReceivedErrors() {
            object[] results = this.Invoke("GetReceivedErrors", new object[0]);
            return ((ReceivedError[])(results[0]));
        }
        
        /// <remarks/>
        public void GetReceivedErrorsAsync() {
            this.GetReceivedErrorsAsync(null);
        }
        
        /// <remarks/>
        public void GetReceivedErrorsAsync(object userState) {
            if ((this.GetReceivedErrorsOperationCompleted == null)) {
                this.GetReceivedErrorsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetReceivedErrorsOperationCompleted);
            }
            this.InvokeAsync("GetReceivedErrors", new object[0], this.GetReceivedErrorsOperationCompleted, userState);
        }
        
        private void OnGetReceivedErrorsOperationCompleted(object arg) {
            if ((this.GetReceivedErrorsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetReceivedErrorsCompleted(this, new GetReceivedErrorsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://APASProxy.DataTypes/2007/04")]
    public partial class SentTransferRequestsFilter {
        
        private bool responseRecievedField;
        
        private string uUIDField;
        
        private string agencyAssignedIdField;
        
        private string recipientSourceIdField;
        
        private System.DateTime sentFromField;
        
        private string requestTrackingIdField;
        
        private System.DateTime sentToField;
        
        /// <remarks/>
        public bool ResponseRecieved {
            get {
                return this.responseRecievedField;
            }
            set {
                this.responseRecievedField = value;
            }
        }
        
        /// <remarks/>
        public string UUID {
            get {
                return this.uUIDField;
            }
            set {
                this.uUIDField = value;
            }
        }
        
        /// <remarks/>
        public string AgencyAssignedId {
            get {
                return this.agencyAssignedIdField;
            }
            set {
                this.agencyAssignedIdField = value;
            }
        }
        
        /// <remarks/>
        public string RecipientSourceId {
            get {
                return this.recipientSourceIdField;
            }
            set {
                this.recipientSourceIdField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime SentFrom {
            get {
                return this.sentFromField;
            }
            set {
                this.sentFromField = value;
            }
        }
        
        /// <remarks/>
        public string RequestTrackingId {
            get {
                return this.requestTrackingIdField;
            }
            set {
                this.requestTrackingIdField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime SentTo {
            get {
                return this.sentToField;
            }
            set {
                this.sentToField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://APASProxy.DataTypes/2007/04")]
    public partial class ReceivedError {
        
        private System.Guid uUIDField;
        
        private string originalMessagePayloadTypeField;
        
        private string originalMessageBodyField;
        
        private string errorMessageField;
        
        private System.DateTime receivedField;
        
        /// <remarks/>
        public System.Guid UUID {
            get {
                return this.uUIDField;
            }
            set {
                this.uUIDField = value;
            }
        }
        
        /// <remarks/>
        public string OriginalMessagePayloadType {
            get {
                return this.originalMessagePayloadTypeField;
            }
            set {
                this.originalMessagePayloadTypeField = value;
            }
        }
        
        /// <remarks/>
        public string OriginalMessageBody {
            get {
                return this.originalMessageBodyField;
            }
            set {
                this.originalMessageBodyField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Received {
            get {
                return this.receivedField;
            }
            set {
                this.receivedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://APASProxy.DataTypes/2007/04")]
    public partial class SentApplicationsFilter {
        
        private string uUIDField;
        
        private string agencyAssignedIdField;
        
        private int applicationIdField;
        
        private string recipientSourceIdField;
        
        private System.DateTime sentFromField;
        
        private System.DateTime sentToField;
        
        /// <remarks/>
        public string UUID {
            get {
                return this.uUIDField;
            }
            set {
                this.uUIDField = value;
            }
        }
        
        /// <remarks/>
        public string AgencyAssignedId {
            get {
                return this.agencyAssignedIdField;
            }
            set {
                this.agencyAssignedIdField = value;
            }
        }
        
        /// <remarks/>
        public int ApplicationId {
            get {
                return this.applicationIdField;
            }
            set {
                this.applicationIdField = value;
            }
        }
        
        /// <remarks/>
        public string RecipientSourceId {
            get {
                return this.recipientSourceIdField;
            }
            set {
                this.recipientSourceIdField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime SentFrom {
            get {
                return this.sentFromField;
            }
            set {
                this.sentFromField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime SentTo {
            get {
                return this.sentToField;
            }
            set {
                this.sentToField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://APASProxy.DataTypes/2007/04")]
    public partial class ReceivedApplication {
        
        private System.Guid uUIDField;
        
        private string agencyAssignedIDField;
        
        private System.DateTime receivedField;
        
        private string educationalInstitutionSourceIdField;
        
        private Application applicationField;
        
        /// <remarks/>
        public System.Guid UUID {
            get {
                return this.uUIDField;
            }
            set {
                this.uUIDField = value;
            }
        }
        
        /// <remarks/>
        public string AgencyAssignedID {
            get {
                return this.agencyAssignedIDField;
            }
            set {
                this.agencyAssignedIDField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Received {
            get {
                return this.receivedField;
            }
            set {
                this.receivedField = value;
            }
        }
        
        /// <remarks/>
        public string EducationalInstitutionSourceId {
            get {
                return this.educationalInstitutionSourceIdField;
            }
            set {
                this.educationalInstitutionSourceIdField = value;
            }
        }
        
        /// <remarks/>
        public Application Application {
            get {
                return this.applicationField;
            }
            set {
                this.applicationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://APASProxy.DataTypes/2007/04")]
    public partial class Application {
        
        private string applicationBodyField;
        
        private string agencyAssignedIdField;
        
        /// <remarks/>
        public string ApplicationBody {
            get {
                return this.applicationBodyField;
            }
            set {
                this.applicationBodyField = value;
            }
        }
        
        /// <remarks/>
        public string AgencyAssignedId {
            get {
                return this.agencyAssignedIdField;
            }
            set {
                this.agencyAssignedIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://APASProxy.DataTypes/2007/04")]
    public partial class ReceivedApplicationsFilter {
        
        private string uUIDField;
        
        private bool newMessagesOnlyField;
        
        private string agencyAssignedIDField;
        
        private string educationalInstitutionSourceIdField;
        
        private System.DateTime receivedFromField;
        
        private System.DateTime receivedToField;
        
        private int applicationIdField;
        
        /// <remarks/>
        public string UUID {
            get {
                return this.uUIDField;
            }
            set {
                this.uUIDField = value;
            }
        }
        
        /// <remarks/>
        public bool NewMessagesOnly {
            get {
                return this.newMessagesOnlyField;
            }
            set {
                this.newMessagesOnlyField = value;
            }
        }
        
        /// <remarks/>
        public string AgencyAssignedID {
            get {
                return this.agencyAssignedIDField;
            }
            set {
                this.agencyAssignedIDField = value;
            }
        }
        
        /// <remarks/>
        public string EducationalInstitutionSourceId {
            get {
                return this.educationalInstitutionSourceIdField;
            }
            set {
                this.educationalInstitutionSourceIdField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ReceivedFrom {
            get {
                return this.receivedFromField;
            }
            set {
                this.receivedFromField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ReceivedTo {
            get {
                return this.receivedToField;
            }
            set {
                this.receivedToField = value;
            }
        }
        
        /// <remarks/>
        public int ApplicationId {
            get {
                return this.applicationIdField;
            }
            set {
                this.applicationIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://APASProxy.DataTypes/2007/04")]
    public partial class RegisteredEducationalInstitution {
        
        private string sourceIdField;
        
        private string educationalInstitutionNameField;
        
        /// <remarks/>
        public string SourceId {
            get {
                return this.sourceIdField;
            }
            set {
                this.sourceIdField = value;
            }
        }
        
        /// <remarks/>
        public string EducationalInstitutionName {
            get {
                return this.educationalInstitutionNameField;
            }
            set {
                this.educationalInstitutionNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://APASProxy.DataTypes/2007/04")]
    public partial class SentApplication {
        
        private System.Guid uUIDField;
        
        private string agencyAssignedIdField;
        
        private System.DateTime sentField;
        
        private string responseBodyField;
        
        private string recipientSourceIdField;
        
        private Application applicationField;
        
        private bool errorOccurredField;
        
        /// <remarks/>
        public System.Guid UUID {
            get {
                return this.uUIDField;
            }
            set {
                this.uUIDField = value;
            }
        }
        
        /// <remarks/>
        public string AgencyAssignedId {
            get {
                return this.agencyAssignedIdField;
            }
            set {
                this.agencyAssignedIdField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Sent {
            get {
                return this.sentField;
            }
            set {
                this.sentField = value;
            }
        }
        
        /// <remarks/>
        public string ResponseBody {
            get {
                return this.responseBodyField;
            }
            set {
                this.responseBodyField = value;
            }
        }
        
        /// <remarks/>
        public string RecipientSourceId {
            get {
                return this.recipientSourceIdField;
            }
            set {
                this.recipientSourceIdField = value;
            }
        }
        
        /// <remarks/>
        public Application Application {
            get {
                return this.applicationField;
            }
            set {
                this.applicationField = value;
            }
        }
        
        /// <remarks/>
        public bool ErrorOccurred {
            get {
                return this.errorOccurredField;
            }
            set {
                this.errorOccurredField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://APASProxy.DataTypes/2007/04")]
    public partial class Acknowledgment {
        
        private string originatorField;
        
        private string originatorAPASCodeField;
        
        private bool isSuccessfulField;
        
        private string acknowledgmentValueField;
        
        /// <remarks/>
        public string Originator {
            get {
                return this.originatorField;
            }
            set {
                this.originatorField = value;
            }
        }
        
        /// <remarks/>
        public string OriginatorAPASCode {
            get {
                return this.originatorAPASCodeField;
            }
            set {
                this.originatorAPASCodeField = value;
            }
        }
        
        /// <remarks/>
        public bool IsSuccessful {
            get {
                return this.isSuccessfulField;
            }
            set {
                this.isSuccessfulField = value;
            }
        }
        
        /// <remarks/>
        public string AcknowledgmentValue {
            get {
                return this.acknowledgmentValueField;
            }
            set {
                this.acknowledgmentValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://APASProxy.DataTypes/2007/04")]
    public partial class ReceivedTransferRequest {
        
        private string agencyAssignedIDField;
        
        private string requestBodyField;
        
        private string uUIDField;
        
        private string requestTrackingIdField;
        
        private string educationalInstitutionSourceIdField;
        
        private System.DateTime receivedField;
        
        /// <remarks/>
        public string AgencyAssignedID {
            get {
                return this.agencyAssignedIDField;
            }
            set {
                this.agencyAssignedIDField = value;
            }
        }
        
        /// <remarks/>
        public string RequestBody {
            get {
                return this.requestBodyField;
            }
            set {
                this.requestBodyField = value;
            }
        }
        
        /// <remarks/>
        public string UUID {
            get {
                return this.uUIDField;
            }
            set {
                this.uUIDField = value;
            }
        }
        
        /// <remarks/>
        public string RequestTrackingId {
            get {
                return this.requestTrackingIdField;
            }
            set {
                this.requestTrackingIdField = value;
            }
        }
        
        /// <remarks/>
        public string EducationalInstitutionSourceId {
            get {
                return this.educationalInstitutionSourceIdField;
            }
            set {
                this.educationalInstitutionSourceIdField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Received {
            get {
                return this.receivedField;
            }
            set {
                this.receivedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://APASProxy.DataTypes/2007/04")]
    public partial class ReceivedTransferRequestsFilter {
        
        private string agencyAssignedIDField;
        
        private string requestTrackingIdField;
        
        private string uUIDField;
        
        private bool newMessagesOnlyField;
        
        private bool responseSentField;
        
        private string educationalInstitutionSourceIdField;
        
        private System.DateTime receivedFromField;
        
        private System.DateTime receivedToField;
        
        /// <remarks/>
        public string AgencyAssignedID {
            get {
                return this.agencyAssignedIDField;
            }
            set {
                this.agencyAssignedIDField = value;
            }
        }
        
        /// <remarks/>
        public string RequestTrackingId {
            get {
                return this.requestTrackingIdField;
            }
            set {
                this.requestTrackingIdField = value;
            }
        }
        
        /// <remarks/>
        public string UUID {
            get {
                return this.uUIDField;
            }
            set {
                this.uUIDField = value;
            }
        }
        
        /// <remarks/>
        public bool NewMessagesOnly {
            get {
                return this.newMessagesOnlyField;
            }
            set {
                this.newMessagesOnlyField = value;
            }
        }
        
        /// <remarks/>
        public bool ResponseSent {
            get {
                return this.responseSentField;
            }
            set {
                this.responseSentField = value;
            }
        }
        
        /// <remarks/>
        public string EducationalInstitutionSourceId {
            get {
                return this.educationalInstitutionSourceIdField;
            }
            set {
                this.educationalInstitutionSourceIdField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ReceivedFrom {
            get {
                return this.receivedFromField;
            }
            set {
                this.receivedFromField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ReceivedTo {
            get {
                return this.receivedToField;
            }
            set {
                this.receivedToField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://APASProxy.DataTypes/2007/04")]
    public partial class ReceivedTranscript {
        
        private string uUIDField;
        
        private string agencyAssignedIDField;
        
        private System.DateTime receivedField;
        
        private string educationalInstitutionSourceIdField;
        
        private Transcript transcriptField;
        
        private string requestTrackingIdField;
        
        /// <remarks/>
        public string UUID {
            get {
                return this.uUIDField;
            }
            set {
                this.uUIDField = value;
            }
        }
        
        /// <remarks/>
        public string AgencyAssignedID {
            get {
                return this.agencyAssignedIDField;
            }
            set {
                this.agencyAssignedIDField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Received {
            get {
                return this.receivedField;
            }
            set {
                this.receivedField = value;
            }
        }
        
        /// <remarks/>
        public string EducationalInstitutionSourceId {
            get {
                return this.educationalInstitutionSourceIdField;
            }
            set {
                this.educationalInstitutionSourceIdField = value;
            }
        }
        
        /// <remarks/>
        public Transcript Transcript {
            get {
                return this.transcriptField;
            }
            set {
                this.transcriptField = value;
            }
        }
        
        /// <remarks/>
        public string RequestTrackingId {
            get {
                return this.requestTrackingIdField;
            }
            set {
                this.requestTrackingIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://APASProxy.DataTypes/2007/04")]
    public partial class Transcript {
        
        private string agencyAssignedIdField;
        
        private string transcriptBodyField;
        
        /// <remarks/>
        public string AgencyAssignedId {
            get {
                return this.agencyAssignedIdField;
            }
            set {
                this.agencyAssignedIdField = value;
            }
        }
        
        /// <remarks/>
        public string TranscriptBody {
            get {
                return this.transcriptBodyField;
            }
            set {
                this.transcriptBodyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://APASProxy.DataTypes/2007/04")]
    public partial class ReceivedTranscriptsFilter {
        
        private string agencyAssignedIDField;
        
        private string uUIDField;
        
        private string requestTrackingIdField;
        
        private bool newMessagesOnlyField;
        
        private string educationalInstitutionSourceIdField;
        
        private System.DateTime receivedFromField;
        
        private System.DateTime receivedToField;
        
        /// <remarks/>
        public string AgencyAssignedID {
            get {
                return this.agencyAssignedIDField;
            }
            set {
                this.agencyAssignedIDField = value;
            }
        }
        
        /// <remarks/>
        public string UUID {
            get {
                return this.uUIDField;
            }
            set {
                this.uUIDField = value;
            }
        }
        
        /// <remarks/>
        public string RequestTrackingId {
            get {
                return this.requestTrackingIdField;
            }
            set {
                this.requestTrackingIdField = value;
            }
        }
        
        /// <remarks/>
        public bool NewMessagesOnly {
            get {
                return this.newMessagesOnlyField;
            }
            set {
                this.newMessagesOnlyField = value;
            }
        }
        
        /// <remarks/>
        public string EducationalInstitutionSourceId {
            get {
                return this.educationalInstitutionSourceIdField;
            }
            set {
                this.educationalInstitutionSourceIdField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ReceivedFrom {
            get {
                return this.receivedFromField;
            }
            set {
                this.receivedFromField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ReceivedTo {
            get {
                return this.receivedToField;
            }
            set {
                this.receivedToField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://APASProxy.DataTypes/2007/04")]
    public partial class SentTranscript {
        
        private string uUIDField;
        
        private string respondingToRequestUUIDField;
        
        private string agencyAssignedIdField;
        
        private System.DateTime sentField;
        
        private string recipientSourceIdField;
        
        private Transcript transcriptField;
        
        private string responseBodyField;
        
        private string requestTrackingIdField;
        
        private bool errorOccurredField;
        
        /// <remarks/>
        public string UUID {
            get {
                return this.uUIDField;
            }
            set {
                this.uUIDField = value;
            }
        }
        
        /// <remarks/>
        public string RespondingToRequestUUID {
            get {
                return this.respondingToRequestUUIDField;
            }
            set {
                this.respondingToRequestUUIDField = value;
            }
        }
        
        /// <remarks/>
        public string AgencyAssignedId {
            get {
                return this.agencyAssignedIdField;
            }
            set {
                this.agencyAssignedIdField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Sent {
            get {
                return this.sentField;
            }
            set {
                this.sentField = value;
            }
        }
        
        /// <remarks/>
        public string RecipientSourceId {
            get {
                return this.recipientSourceIdField;
            }
            set {
                this.recipientSourceIdField = value;
            }
        }
        
        /// <remarks/>
        public Transcript Transcript {
            get {
                return this.transcriptField;
            }
            set {
                this.transcriptField = value;
            }
        }
        
        /// <remarks/>
        public string ResponseBody {
            get {
                return this.responseBodyField;
            }
            set {
                this.responseBodyField = value;
            }
        }
        
        /// <remarks/>
        public string RequestTrackingId {
            get {
                return this.requestTrackingIdField;
            }
            set {
                this.requestTrackingIdField = value;
            }
        }
        
        /// <remarks/>
        public bool ErrorOccurred {
            get {
                return this.errorOccurredField;
            }
            set {
                this.errorOccurredField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://APASProxy.DataTypes/2007/04")]
    public partial class SentTranscriptsFilter {
        
        private string uUIDField;
        
        private string agencyAssignedIdField;
        
        private string requestTrackingIdField;
        
        private string recipientSourceIdField;
        
        private System.DateTime sentFromField;
        
        private System.DateTime sentToField;
        
        /// <remarks/>
        public string UUID {
            get {
                return this.uUIDField;
            }
            set {
                this.uUIDField = value;
            }
        }
        
        /// <remarks/>
        public string AgencyAssignedId {
            get {
                return this.agencyAssignedIdField;
            }
            set {
                this.agencyAssignedIdField = value;
            }
        }
        
        /// <remarks/>
        public string RequestTrackingId {
            get {
                return this.requestTrackingIdField;
            }
            set {
                this.requestTrackingIdField = value;
            }
        }
        
        /// <remarks/>
        public string RecipientSourceId {
            get {
                return this.recipientSourceIdField;
            }
            set {
                this.recipientSourceIdField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime SentFrom {
            get {
                return this.sentFromField;
            }
            set {
                this.sentFromField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime SentTo {
            get {
                return this.sentToField;
            }
            set {
                this.sentToField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://APASProxy.DataTypes/2007/04")]
    public partial class SentTransferRequest {
        
        private string transferRequestBodyField;
        
        private string requestTrackingIdField;
        
        private string uUIDField;
        
        private string agencyAssignedIDField;
        
        private string recipientSourceIdField;
        
        private System.DateTime sentField;
        
        private string responseBodyField;
        
        private bool errorOccurredField;
        
        /// <remarks/>
        public string TransferRequestBody {
            get {
                return this.transferRequestBodyField;
            }
            set {
                this.transferRequestBodyField = value;
            }
        }
        
        /// <remarks/>
        public string RequestTrackingId {
            get {
                return this.requestTrackingIdField;
            }
            set {
                this.requestTrackingIdField = value;
            }
        }
        
        /// <remarks/>
        public string UUID {
            get {
                return this.uUIDField;
            }
            set {
                this.uUIDField = value;
            }
        }
        
        /// <remarks/>
        public string AgencyAssignedID {
            get {
                return this.agencyAssignedIDField;
            }
            set {
                this.agencyAssignedIDField = value;
            }
        }
        
        /// <remarks/>
        public string RecipientSourceId {
            get {
                return this.recipientSourceIdField;
            }
            set {
                this.recipientSourceIdField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Sent {
            get {
                return this.sentField;
            }
            set {
                this.sentField = value;
            }
        }
        
        /// <remarks/>
        public string ResponseBody {
            get {
                return this.responseBodyField;
            }
            set {
                this.responseBodyField = value;
            }
        }
        
        /// <remarks/>
        public bool ErrorOccurred {
            get {
                return this.errorOccurredField;
            }
            set {
                this.errorOccurredField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetSentTransferRequestsCompletedEventHandler(object sender, GetSentTransferRequestsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSentTransferRequestsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSentTransferRequestsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SentTransferRequest[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SentTransferRequest[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetSentTranscriptsCompletedEventHandler(object sender, GetSentTranscriptsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSentTranscriptsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSentTranscriptsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SentTranscript[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SentTranscript[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetReceivedTranscriptsCompletedEventHandler(object sender, GetReceivedTranscriptsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetReceivedTranscriptsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetReceivedTranscriptsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReceivedTranscript[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReceivedTranscript[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetReceivedTransferRequestsCompletedEventHandler(object sender, GetReceivedTransferRequestsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetReceivedTransferRequestsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetReceivedTransferRequestsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReceivedTransferRequest[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReceivedTransferRequest[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void SendTrancriptCompletedEventHandler(object sender, SendTrancriptCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendTrancriptCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendTrancriptCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Acknowledgment Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Acknowledgment)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void SendTransferRequestCompletedEventHandler(object sender, SendTransferRequestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendTransferRequestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendTransferRequestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Acknowledgment Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Acknowledgment)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void SendApplicationCompletedEventHandler(object sender, SendApplicationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendApplicationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendApplicationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Acknowledgment Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Acknowledgment)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetHostInstitutionCompletedEventHandler(object sender, GetHostInstitutionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetHostInstitutionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetHostInstitutionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RegisteredEducationalInstitution Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RegisteredEducationalInstitution)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetDecompressedDecodedMessageCompletedEventHandler(object sender, GetDecompressedDecodedMessageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDecompressedDecodedMessageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDecompressedDecodedMessageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void PrepareCompressedEncodedMessageCompletedEventHandler(object sender, PrepareCompressedEncodedMessageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PrepareCompressedEncodedMessageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PrepareCompressedEncodedMessageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetReceivedApplicationsCompletedEventHandler(object sender, GetReceivedApplicationsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetReceivedApplicationsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetReceivedApplicationsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReceivedApplication[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReceivedApplication[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetSentApplicationsCompletedEventHandler(object sender, GetSentApplicationsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSentApplicationsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSentApplicationsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SentApplication[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SentApplication[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetRegisteredEducationalInstitutionsCompletedEventHandler(object sender, GetRegisteredEducationalInstitutionsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRegisteredEducationalInstitutionsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRegisteredEducationalInstitutionsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RegisteredEducationalInstitution[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RegisteredEducationalInstitution[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetReceivedErrorsCompletedEventHandler(object sender, GetReceivedErrorsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetReceivedErrorsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetReceivedErrorsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReceivedError[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReceivedError[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591