//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Lcapas.Core.quesvc2 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="APASQueueServiceExt2", Namespace="http://APASProxy.ServiceContracts/2010/06")]
    public partial class APASQueueServiceExt2 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetReceivedErrorsByConsumerOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetReceivedTransferRequestsByConsumerOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetReceivedTranscriptsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetReceivedTranscriptsByConsumerOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetReceivedApplicationsByConsumerOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public APASQueueServiceExt2() {
            this.Url = global::Lcapas.Core.Properties.Settings.Default.LcapasCore_quesvcext2_APASQueueServiceExt2;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetReceivedErrorsByConsumerCompletedEventHandler GetReceivedErrorsByConsumerCompleted;
        
        /// <remarks/>
        public event GetReceivedTransferRequestsByConsumerCompletedEventHandler GetReceivedTransferRequestsByConsumerCompleted;
        
        /// <remarks/>
        public event GetReceivedTranscriptsCompletedEventHandler GetReceivedTranscriptsCompleted;
        
        /// <remarks/>
        public event GetReceivedTranscriptsByConsumerCompletedEventHandler GetReceivedTranscriptsByConsumerCompleted;
        
        /// <remarks/>
        public event GetReceivedApplicationsByConsumerCompletedEventHandler GetReceivedApplicationsByConsumerCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://APASProxy.ServiceContracts/2010/06/GetReceivedErrorsByConsumer", RequestNamespace="http://APASProxy.ServiceContracts/2010/06", ResponseNamespace="http://APASProxy.ServiceContracts/2010/06", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ReceivedError[] GetReceivedErrorsByConsumer(string serviceConsumerId) {
            object[] results = this.Invoke("GetReceivedErrorsByConsumer", new object[] {
                        serviceConsumerId});
            return ((ReceivedError[])(results[0]));
        }
        
        /// <remarks/>
        public void GetReceivedErrorsByConsumerAsync(string serviceConsumerId) {
            this.GetReceivedErrorsByConsumerAsync(serviceConsumerId, null);
        }
        
        /// <remarks/>
        public void GetReceivedErrorsByConsumerAsync(string serviceConsumerId, object userState) {
            if ((this.GetReceivedErrorsByConsumerOperationCompleted == null)) {
                this.GetReceivedErrorsByConsumerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetReceivedErrorsByConsumerOperationCompleted);
            }
            this.InvokeAsync("GetReceivedErrorsByConsumer", new object[] {
                        serviceConsumerId}, this.GetReceivedErrorsByConsumerOperationCompleted, userState);
        }
        
        private void OnGetReceivedErrorsByConsumerOperationCompleted(object arg) {
            if ((this.GetReceivedErrorsByConsumerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetReceivedErrorsByConsumerCompleted(this, new GetReceivedErrorsByConsumerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://APASProxy.ServiceContracts/2010/06/GetReceivedTransferRequestsByConsumer", RequestNamespace="http://APASProxy.ServiceContracts/2010/06", ResponseNamespace="http://APASProxy.ServiceContracts/2010/06", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ReceivedTransferRequest[] GetReceivedTransferRequestsByConsumer(string serviceConsumerId) {
            object[] results = this.Invoke("GetReceivedTransferRequestsByConsumer", new object[] {
                        serviceConsumerId});
            return ((ReceivedTransferRequest[])(results[0]));
        }
        
        /// <remarks/>
        public void GetReceivedTransferRequestsByConsumerAsync(string serviceConsumerId) {
            this.GetReceivedTransferRequestsByConsumerAsync(serviceConsumerId, null);
        }
        
        /// <remarks/>
        public void GetReceivedTransferRequestsByConsumerAsync(string serviceConsumerId, object userState) {
            if ((this.GetReceivedTransferRequestsByConsumerOperationCompleted == null)) {
                this.GetReceivedTransferRequestsByConsumerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetReceivedTransferRequestsByConsumerOperationCompleted);
            }
            this.InvokeAsync("GetReceivedTransferRequestsByConsumer", new object[] {
                        serviceConsumerId}, this.GetReceivedTransferRequestsByConsumerOperationCompleted, userState);
        }
        
        private void OnGetReceivedTransferRequestsByConsumerOperationCompleted(object arg) {
            if ((this.GetReceivedTransferRequestsByConsumerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetReceivedTransferRequestsByConsumerCompleted(this, new GetReceivedTransferRequestsByConsumerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://APASProxy.ServiceContracts/2010/06/GetReceivedTranscripts", RequestNamespace="http://APASProxy.ServiceContracts/2010/06", ResponseNamespace="http://APASProxy.ServiceContracts/2010/06", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ReceivedTranscript[] GetReceivedTranscripts([System.Xml.Serialization.XmlElementAttribute(Namespace="http://APASProxy.DataTypes/2010/06")] ReceivedTranscriptsFilter receivedTranscriptsFilter) {
            object[] results = this.Invoke("GetReceivedTranscripts", new object[] {
                        receivedTranscriptsFilter});
            return ((ReceivedTranscript[])(results[0]));
        }
        
        /// <remarks/>
        public void GetReceivedTranscriptsAsync(ReceivedTranscriptsFilter receivedTranscriptsFilter) {
            this.GetReceivedTranscriptsAsync(receivedTranscriptsFilter, null);
        }
        
        /// <remarks/>
        public void GetReceivedTranscriptsAsync(ReceivedTranscriptsFilter receivedTranscriptsFilter, object userState) {
            if ((this.GetReceivedTranscriptsOperationCompleted == null)) {
                this.GetReceivedTranscriptsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetReceivedTranscriptsOperationCompleted);
            }
            this.InvokeAsync("GetReceivedTranscripts", new object[] {
                        receivedTranscriptsFilter}, this.GetReceivedTranscriptsOperationCompleted, userState);
        }
        
        private void OnGetReceivedTranscriptsOperationCompleted(object arg) {
            if ((this.GetReceivedTranscriptsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetReceivedTranscriptsCompleted(this, new GetReceivedTranscriptsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://APASProxy.ServiceContracts/2010/06/GetReceivedTranscriptsByConsumer", RequestNamespace="http://APASProxy.ServiceContracts/2010/06", ResponseNamespace="http://APASProxy.ServiceContracts/2010/06", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ReceivedTranscript[] GetReceivedTranscriptsByConsumer(string serviceConsumerId, int maximumToReturn) {
            object[] results = this.Invoke("GetReceivedTranscriptsByConsumer", new object[] {
                        serviceConsumerId,
                        maximumToReturn});
            return ((ReceivedTranscript[])(results[0]));
        }
        
        /// <remarks/>
        public void GetReceivedTranscriptsByConsumerAsync(string serviceConsumerId, int maximumToReturn) {
            this.GetReceivedTranscriptsByConsumerAsync(serviceConsumerId, maximumToReturn, null);
        }
        
        /// <remarks/>
        public void GetReceivedTranscriptsByConsumerAsync(string serviceConsumerId, int maximumToReturn, object userState) {
            if ((this.GetReceivedTranscriptsByConsumerOperationCompleted == null)) {
                this.GetReceivedTranscriptsByConsumerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetReceivedTranscriptsByConsumerOperationCompleted);
            }
            this.InvokeAsync("GetReceivedTranscriptsByConsumer", new object[] {
                        serviceConsumerId,
                        maximumToReturn}, this.GetReceivedTranscriptsByConsumerOperationCompleted, userState);
        }
        
        private void OnGetReceivedTranscriptsByConsumerOperationCompleted(object arg) {
            if ((this.GetReceivedTranscriptsByConsumerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetReceivedTranscriptsByConsumerCompleted(this, new GetReceivedTranscriptsByConsumerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://APASProxy.ServiceContracts/2010/06/GetReceivedApplicationsByConsumer", RequestNamespace="http://APASProxy.ServiceContracts/2010/06", ResponseNamespace="http://APASProxy.ServiceContracts/2010/06", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ReceivedApplication[] GetReceivedApplicationsByConsumer(string serviceConsumerId) {
            object[] results = this.Invoke("GetReceivedApplicationsByConsumer", new object[] {
                        serviceConsumerId});
            return ((ReceivedApplication[])(results[0]));
        }
        
        /// <remarks/>
        public void GetReceivedApplicationsByConsumerAsync(string serviceConsumerId) {
            this.GetReceivedApplicationsByConsumerAsync(serviceConsumerId, null);
        }
        
        /// <remarks/>
        public void GetReceivedApplicationsByConsumerAsync(string serviceConsumerId, object userState) {
            if ((this.GetReceivedApplicationsByConsumerOperationCompleted == null)) {
                this.GetReceivedApplicationsByConsumerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetReceivedApplicationsByConsumerOperationCompleted);
            }
            this.InvokeAsync("GetReceivedApplicationsByConsumer", new object[] {
                        serviceConsumerId}, this.GetReceivedApplicationsByConsumerOperationCompleted, userState);
        }
        
        private void OnGetReceivedApplicationsByConsumerOperationCompleted(object arg) {
            if ((this.GetReceivedApplicationsByConsumerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetReceivedApplicationsByConsumerCompleted(this, new GetReceivedApplicationsByConsumerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://APASProxy.DataTypes/2007/04")]
    public partial class ReceivedError {
        
        private System.Guid uUIDField;
        
        private string originalMessagePayloadTypeField;
        
        private string originalMessageBodyField;
        
        private string errorMessageField;
        
        private System.DateTime receivedField;
        
        /// <remarks/>
        public System.Guid UUID {
            get {
                return this.uUIDField;
            }
            set {
                this.uUIDField = value;
            }
        }
        
        /// <remarks/>
        public string OriginalMessagePayloadType {
            get {
                return this.originalMessagePayloadTypeField;
            }
            set {
                this.originalMessagePayloadTypeField = value;
            }
        }
        
        /// <remarks/>
        public string OriginalMessageBody {
            get {
                return this.originalMessageBodyField;
            }
            set {
                this.originalMessageBodyField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Received {
            get {
                return this.receivedField;
            }
            set {
                this.receivedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://APASProxy.DataTypes/2007/04")]
    public partial class Application {
        
        private string applicationBodyField;
        
        private string agencyAssignedIdField;
        
        /// <remarks/>
        public string ApplicationBody {
            get {
                return this.applicationBodyField;
            }
            set {
                this.applicationBodyField = value;
            }
        }
        
        /// <remarks/>
        public string AgencyAssignedId {
            get {
                return this.agencyAssignedIdField;
            }
            set {
                this.agencyAssignedIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://APASProxy.DataTypes/2007/04")]
    public partial class ReceivedApplication {
        
        private System.Guid uUIDField;
        
        private string agencyAssignedIDField;
        
        private System.DateTime receivedField;
        
        private string educationalInstitutionSourceIdField;
        
        private Application applicationField;
        
        /// <remarks/>
        public System.Guid UUID {
            get {
                return this.uUIDField;
            }
            set {
                this.uUIDField = value;
            }
        }
        
        /// <remarks/>
        public string AgencyAssignedID {
            get {
                return this.agencyAssignedIDField;
            }
            set {
                this.agencyAssignedIDField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Received {
            get {
                return this.receivedField;
            }
            set {
                this.receivedField = value;
            }
        }
        
        /// <remarks/>
        public string EducationalInstitutionSourceId {
            get {
                return this.educationalInstitutionSourceIdField;
            }
            set {
                this.educationalInstitutionSourceIdField = value;
            }
        }
        
        /// <remarks/>
        public Application Application {
            get {
                return this.applicationField;
            }
            set {
                this.applicationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://APASProxy.DataTypes/2007/04")]
    public partial class Transcript {
        
        private string agencyAssignedIdField;
        
        private string transcriptBodyField;
        
        /// <remarks/>
        public string AgencyAssignedId {
            get {
                return this.agencyAssignedIdField;
            }
            set {
                this.agencyAssignedIdField = value;
            }
        }
        
        /// <remarks/>
        public string TranscriptBody {
            get {
                return this.transcriptBodyField;
            }
            set {
                this.transcriptBodyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://APASProxy.DataTypes/2007/04")]
    public partial class ReceivedTranscript {
        
        private string uUIDField;
        
        private string agencyAssignedIDField;
        
        private System.DateTime receivedField;
        
        private string educationalInstitutionSourceIdField;
        
        private Transcript transcriptField;
        
        private string requestTrackingIdField;
        
        /// <remarks/>
        public string UUID {
            get {
                return this.uUIDField;
            }
            set {
                this.uUIDField = value;
            }
        }
        
        /// <remarks/>
        public string AgencyAssignedID {
            get {
                return this.agencyAssignedIDField;
            }
            set {
                this.agencyAssignedIDField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Received {
            get {
                return this.receivedField;
            }
            set {
                this.receivedField = value;
            }
        }
        
        /// <remarks/>
        public string EducationalInstitutionSourceId {
            get {
                return this.educationalInstitutionSourceIdField;
            }
            set {
                this.educationalInstitutionSourceIdField = value;
            }
        }
        
        /// <remarks/>
        public Transcript Transcript {
            get {
                return this.transcriptField;
            }
            set {
                this.transcriptField = value;
            }
        }
        
        /// <remarks/>
        public string RequestTrackingId {
            get {
                return this.requestTrackingIdField;
            }
            set {
                this.requestTrackingIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://APASProxy.DataTypes/2010/06")]
    public partial class ReceivedTranscriptsFilter {
        
        private string agencyAssignedIDField;
        
        private string uUIDField;
        
        private string requestTrackingIdField;
        
        private string educationalInstitutionSourceIdField;
        
        private System.DateTime receivedFromField;
        
        private System.DateTime receivedToField;
        
        private int totalReceivedField;
        
        private int maximumToReturnField;
        
        /// <remarks/>
        public string AgencyAssignedID {
            get {
                return this.agencyAssignedIDField;
            }
            set {
                this.agencyAssignedIDField = value;
            }
        }
        
        /// <remarks/>
        public string UUID {
            get {
                return this.uUIDField;
            }
            set {
                this.uUIDField = value;
            }
        }
        
        /// <remarks/>
        public string RequestTrackingId {
            get {
                return this.requestTrackingIdField;
            }
            set {
                this.requestTrackingIdField = value;
            }
        }
        
        /// <remarks/>
        public string EducationalInstitutionSourceId {
            get {
                return this.educationalInstitutionSourceIdField;
            }
            set {
                this.educationalInstitutionSourceIdField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ReceivedFrom {
            get {
                return this.receivedFromField;
            }
            set {
                this.receivedFromField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ReceivedTo {
            get {
                return this.receivedToField;
            }
            set {
                this.receivedToField = value;
            }
        }
        
        /// <remarks/>
        public int TotalReceived {
            get {
                return this.totalReceivedField;
            }
            set {
                this.totalReceivedField = value;
            }
        }
        
        /// <remarks/>
        public int MaximumToReturn {
            get {
                return this.maximumToReturnField;
            }
            set {
                this.maximumToReturnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://APASProxy.DataTypes/2007/04")]
    public partial class ReceivedTransferRequest {
        
        private string agencyAssignedIDField;
        
        private string requestBodyField;
        
        private string uUIDField;
        
        private string requestTrackingIdField;
        
        private string educationalInstitutionSourceIdField;
        
        private System.DateTime receivedField;
        
        /// <remarks/>
        public string AgencyAssignedID {
            get {
                return this.agencyAssignedIDField;
            }
            set {
                this.agencyAssignedIDField = value;
            }
        }
        
        /// <remarks/>
        public string RequestBody {
            get {
                return this.requestBodyField;
            }
            set {
                this.requestBodyField = value;
            }
        }
        
        /// <remarks/>
        public string UUID {
            get {
                return this.uUIDField;
            }
            set {
                this.uUIDField = value;
            }
        }
        
        /// <remarks/>
        public string RequestTrackingId {
            get {
                return this.requestTrackingIdField;
            }
            set {
                this.requestTrackingIdField = value;
            }
        }
        
        /// <remarks/>
        public string EducationalInstitutionSourceId {
            get {
                return this.educationalInstitutionSourceIdField;
            }
            set {
                this.educationalInstitutionSourceIdField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Received {
            get {
                return this.receivedField;
            }
            set {
                this.receivedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetReceivedErrorsByConsumerCompletedEventHandler(object sender, GetReceivedErrorsByConsumerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetReceivedErrorsByConsumerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetReceivedErrorsByConsumerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReceivedError[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReceivedError[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetReceivedTransferRequestsByConsumerCompletedEventHandler(object sender, GetReceivedTransferRequestsByConsumerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetReceivedTransferRequestsByConsumerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetReceivedTransferRequestsByConsumerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReceivedTransferRequest[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReceivedTransferRequest[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetReceivedTranscriptsCompletedEventHandler(object sender, GetReceivedTranscriptsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetReceivedTranscriptsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetReceivedTranscriptsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReceivedTranscript[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReceivedTranscript[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetReceivedTranscriptsByConsumerCompletedEventHandler(object sender, GetReceivedTranscriptsByConsumerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetReceivedTranscriptsByConsumerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetReceivedTranscriptsByConsumerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReceivedTranscript[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReceivedTranscript[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetReceivedApplicationsByConsumerCompletedEventHandler(object sender, GetReceivedApplicationsByConsumerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetReceivedApplicationsByConsumerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetReceivedApplicationsByConsumerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReceivedApplication[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReceivedApplication[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591