//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lcapas.Core.Models.Colldb
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACAD_CREDENTIALS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ACAD_CREDENTIALS()
        {
            this.ACAD_CREDENTIALS_LS = new HashSet<ACAD_CREDENTIALS_LS>();
            this.STUDENT_ACAD_CRED_LS = new HashSet<STUDENT_ACAD_CRED_LS>();
        }
    
        public string ACAD_CREDENTIALS_ID { get; set; }
        public string ACAD_PERSON_ID { get; set; }
        public string ACAD_INSTITUTIONS_ID { get; set; }
        public Nullable<System.DateTime> ACAD_START_DATE { get; set; }
        public Nullable<System.DateTime> ACAD_END_DATE { get; set; }
        public string ACAD_DEGREE { get; set; }
        public Nullable<System.DateTime> ACAD_DEGREE_DATE { get; set; }
        public string ACAD_DIVISION { get; set; }
        public string ACAD_LOCATION { get; set; }
        public string ACAD_ACAD_LEVEL { get; set; }
        public Nullable<decimal> ACAD_NO_YEARS { get; set; }
        public Nullable<System.DateTime> ACAD_COMMENCEMENT_DATE { get; set; }
        public string ACAD_DIPLOMA_NAME { get; set; }
        public Nullable<decimal> ACAD_GPA { get; set; }
        public Nullable<decimal> ACAD_GPA1 { get; set; }
        public Nullable<decimal> ACAD_GPA2 { get; set; }
        public Nullable<decimal> ACAD_RANK_PERCENT { get; set; }
        public Nullable<decimal> ACAD_RANK_NUMERATOR { get; set; }
        public Nullable<decimal> ACAD_RANK_DENOMINATOR { get; set; }
        public string ACAD_THESIS { get; set; }
        public string ACAD_COMMENTS { get; set; }
        public string ACAD_CREDENTIALS_ADDOPR { get; set; }
        public Nullable<System.DateTime> ACAD_CREDENTIALS_ADDDATE { get; set; }
        public string ACAD_CREDENTIALS_CHGOPR { get; set; }
        public Nullable<System.DateTime> ACAD_CREDENTIALS_CHGDATE { get; set; }
        public string ACAD_TRANSCRIPT_CITY { get; set; }
        public string ACAD_TRANSCRIPT_STATE { get; set; }
        public string ACAD_TRANSCRIPT_ZIP { get; set; }
        public string ACAD_TRANSCRIPT_COUNTRY { get; set; }
        public string ACAD_COMMENCEMENT_SITE { get; set; }
        public string ACAD_USER1 { get; set; }
        public string ACAD_USER2 { get; set; }
        public string ACAD_USER3 { get; set; }
        public string ACAD_USER4 { get; set; }
        public string ACAD_USER5 { get; set; }
        public string ACAD_USER6 { get; set; }
        public string ACAD_USER7 { get; set; }
        public string ACAD_USER8 { get; set; }
        public string ACAD_USER9 { get; set; }
        public string ACAD_USER10 { get; set; }
        public string ACAD_ACAD_PROGRAM { get; set; }
        public string ACAD_CERT_TYPE { get; set; }
        public string ACAD_CERT_STATUS { get; set; }
        public string ACAD_CERT_EMPLOYABLE_BY_CODE { get; set; }
        public string ACAD_CERT_STAFF_REQUEST_FLAG { get; set; }
        public string ACAD_TERM { get; set; }
        public string ACAD_CERT_PART_TIME_IND { get; set; }
        public string ACAD_CERT_PART_TIME_OVR { get; set; }
        public string ACAD_RENEWAL_IND { get; set; }
        public Nullable<decimal> ACAD_INTG_TRANSFER_HRS { get; set; }
        public string ACAD_INTG_KEY_IDX { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACAD_CREDENTIALS_LS> ACAD_CREDENTIALS_LS { get; set; }
        public virtual INSTITUTION INSTITUTION { get; set; }
        public virtual PEOPLE PERSON { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STUDENT_ACAD_CRED_LS> STUDENT_ACAD_CRED_LS { get; set; }
    }
}
