//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lcapas.Core.Models.Colldb
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADDRESS_LS
    {
        public string ADDRESS_ID { get; set; }
        public decimal POS { get; set; }
        public string ADDRESS_LINES { get; set; }
        public string RESIDENTS { get; set; }
        public string FORMER_RESIDENTS { get; set; }
        public string ADDRESS_CHAPTER { get; set; }
        public Nullable<System.DateTime> ADDRESS_START_DATE { get; set; }
        public Nullable<System.DateTime> ADDRESS_END_DATE { get; set; }
        public string ADDR_CHAPTER_IDX { get; set; }
        public string CITY_AND_ADDRESS_IDX { get; set; }
        public string ZIP_IDX { get; set; }
    
        public virtual ADDRESSES ADDRESS { get; set; }
        public virtual PEOPLE PERSON { get; set; }
        public virtual PEOPLE PERSON1 { get; set; }
    }
}
