//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lcapas.Core.Models.Colldb
{
    using System;
    using System.Collections.Generic;
    
    public partial class APPL_LOCATION_INFO
    {
        public string APPLICATIONS_ID { get; set; }
        public decimal POS { get; set; }
        public string APPL_LOCATIONS { get; set; }
        public Nullable<System.DateTime> APPL_LOCATION_DATES { get; set; }
        public string APPL_LOCATION_CHANGE_REASONS { get; set; }
    
        public virtual APPLICATION APPLICATION { get; set; }
    }
}
