//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lcapas.Core.Models.Colldb
{
    using System;
    using System.Collections.Generic;
    
    public partial class APPLICATION_STATUSES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public APPLICATION_STATUSES()
        {
            this.APPL_STATUSES = new HashSet<APPL_STATUSES>();
        }
    
        public string APPLICATION_STATUSES_ID { get; set; }
        public string APPS_DESC { get; set; }
        public string APPS_SPECIAL_PROCESSING_CODE { get; set; }
        public string APPS_COLUMN_NO { get; set; }
        public string APPS_USER1 { get; set; }
        public string APPS_USER2 { get; set; }
        public string APPS_USER3 { get; set; }
        public string APPS_USER4 { get; set; }
        public string APPS_USER5 { get; set; }
        public string APPS_USER6 { get; set; }
        public string APPS_USER7 { get; set; }
        public string APPS_USER8 { get; set; }
        public string APPS_USER9 { get; set; }
        public string APPS_USER10 { get; set; }
        public string APPLICATION_STATUSES_ADDOPR { get; set; }
        public Nullable<System.DateTime> APPLICATION_STATUSES_ADDDATE { get; set; }
        public string APPLICATION_STATUSES_CHGOPR { get; set; }
        public Nullable<System.DateTime> APPLICATION_STATUSES_CHGDATE { get; set; }
        public string APP_INTG_ADM_DEC_TYP_IDX { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APPL_STATUSES> APPL_STATUSES { get; set; }
    }
}
