//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lcapas.Core.Models.Colldb
{
    using System;
    using System.Collections.Generic;
    
    public partial class APPL_STATUSES
    {
        public string APPLICATIONS_ID { get; set; }
        public decimal POS { get; set; }
        public string APPL_STATUS { get; set; }
        public Nullable<System.DateTime> APPL_STATUS_DATE { get; set; }
        public string APPL_DECISION_BY { get; set; }
        public Nullable<System.DateTime> APPL_STATUS_TIME { get; set; }
    
        public virtual APPLICATION APPLICATION { get; set; }
        public virtual APPLICATION_STATUSES APPLICATION_STATUSES { get; set; }
    }
}
