//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lcapas.Core.Models.Colldb
{
    using System;
    using System.Collections.Generic;
    
    public partial class APPLICATION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public APPLICATION()
        {
            this.APPL_STATUSES = new HashSet<APPL_STATUSES>();
            this.APPLICATIONS_LS = new HashSet<APPLICATIONS_LS>();
            this.EXTERNAL_TRANSCRIPTS_LS = new HashSet<EXTERNAL_TRANSCRIPTS_LS>();
            this.PERSON_ST_LS = new HashSet<PERSON_ST_LS>();
            this.APPL_LOCATION_INFO = new HashSet<APPL_LOCATION_INFO>();
        }
    
        public string APPLICATIONS_ID { get; set; }
        public string APPL_APPLICANT { get; set; }
        public string APPL_ACAD_PROGRAM { get; set; }
        public string APPL_NO { get; set; }
        public Nullable<System.DateTime> APPL_DATE { get; set; }
        public string APPL_START_TERM { get; set; }
        public string APPL_STUDENT_LOAD_INTENT { get; set; }
        public string APPL_FA_INTENT_FLAG { get; set; }
        public string APPL_RESIDENCY_STATUS { get; set; }
        public string APPLICATIONS_CHGOPR { get; set; }
        public string APPL_ADMISSIONS_REP { get; set; }
        public Nullable<System.DateTime> APPL_REP_ASSIGN_DATE { get; set; }
        public Nullable<decimal> APPL_RATING { get; set; }
        public Nullable<decimal> APPL_CALC_RATING { get; set; }
        public string APPL_PRIORITY { get; set; }
        public string APPL_STUDENT_TYPE { get; set; }
        public string APPL_ADMIT_STATUS { get; set; }
        public string APPL_RECOMMENDATIONS { get; set; }
        public string APPL_ADMIT_INSTITUTION { get; set; }
        public string APPL_ADMIT_STATE { get; set; }
        public string APPL_ADMIT_COUNTY { get; set; }
        public Nullable<System.DateTime> APPL_FA_SUBMIT_DATE { get; set; }
        public Nullable<System.DateTime> APPL_WITHDRAW_DATE { get; set; }
        public string APPL_WITHDRAW_REASON { get; set; }
        public string APPL_ATTENDED_INSTEAD { get; set; }
        public string APPL_COMMENTS { get; set; }
        public Nullable<System.DateTime> APPLICATIONS_ADDDATE { get; set; }
        public string APPLICATIONS_ADDOPR { get; set; }
        public Nullable<System.DateTime> APPLICATIONS_CHGDATE { get; set; }
        public string APPL_USER1 { get; set; }
        public string APPL_USER2 { get; set; }
        public string APPL_USER3 { get; set; }
        public string APPL_USER4 { get; set; }
        public string APPL_USER5 { get; set; }
        public string APPL_USER6 { get; set; }
        public string APPL_USER7 { get; set; }
        public string APPL_USER8 { get; set; }
        public string APPL_USER9 { get; set; }
        public string APPL_USER10 { get; set; }
        public Nullable<decimal> APPL_CHOICE { get; set; }
        public string APPL_ACTIVE_STU_PROGRAM_FLAG { get; set; }
        public string APPL_SOURCE { get; set; }
        public string APPL_CRM_APPLICATION_NO { get; set; }
        public string APPL_CUSTOM_FIELDS_XML { get; set; }
        public string APPL_REC_ORG_ID { get; set; }
        public string APPL_INTG_APPL_TYPE { get; set; }
        public string APPL_INTG_KEY_IDX { get; set; }
        public string APPL_ADM_ELIGIBILITY { get; set; }
        public string APPL_HIGHER_ED_LVL { get; set; }
        public string APPL_HIGH_SCH_ED_LVL { get; set; }
        public string APPL_HIGHEST_GR_CMPL { get; set; }
        public string APPL_TYPE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APPL_STATUSES> APPL_STATUSES { get; set; }
        public virtual PEOPLE PERSON { get; set; }
        public virtual PEOPLE PERSON1 { get; set; }
        public virtual PEOPLE PERSON2 { get; set; }
        public virtual PERSON_ST PERSON_ST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APPLICATIONS_LS> APPLICATIONS_LS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EXTERNAL_TRANSCRIPTS_LS> EXTERNAL_TRANSCRIPTS_LS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PERSON_ST_LS> PERSON_ST_LS { get; set; }
        public virtual INSTITUTION INSTITUTION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APPL_LOCATION_INFO> APPL_LOCATION_INFO { get; set; }
        public virtual ACAD_PROGRAMS ACAD_PROGRAMS { get; set; }
        public virtual TERM TERM { get; set; }
    }
}
