//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lcapas.Core.Models.Colldb
{
    using System;
    using System.Collections.Generic;
    
    public partial class CC_COMMENTS
    {
        public string CC_COMMENTS_ID { get; set; }
        public string CC_COMMENTS_DESC { get; set; }
        public string CC_COMMENTS_ADD_OPERATOR { get; set; }
        public Nullable<System.DateTime> CC_COMMENTS_ADD_DATE { get; set; }
        public string CC_COMMENTS_CHANGE_OPERATOR { get; set; }
        public Nullable<System.DateTime> CC_COMMENTS_CHANGE_DATE { get; set; }
        public string CC_COMMENTS_TEXT { get; set; }
        public string CC_COMMENTS_PUBLIC { get; set; }
    }
}
