//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lcapas.Core.Models.Colldb
{
    using System;
    using System.Collections.Generic;
    
    public partial class COURSE_SEC_FACULTY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COURSE_SEC_FACULTY()
        {
            this.COURSE_SECTIONS_LS = new HashSet<COURSE_SECTIONS_LS>();
        }
    
        public string COURSE_SEC_FACULTY_ID { get; set; }
        public string CSF_COURSE_SECTION { get; set; }
        public string CSF_FACULTY { get; set; }
        public string CSF_INSTR_METHOD { get; set; }
        public Nullable<decimal> CSF_FACULTY_LOAD { get; set; }
        public string CSF_TEACHING_ARRANGEMENT { get; set; }
        public Nullable<decimal> CSF_FACULTY_PCT { get; set; }
        public Nullable<System.DateTime> CSF_START_DATE { get; set; }
        public Nullable<System.DateTime> CSF_END_DATE { get; set; }
        public Nullable<decimal> CSF_FACULTY_STIPEND { get; set; }
        public string COURSE_SEC_FACULTY_ADDOPR { get; set; }
        public Nullable<System.DateTime> COURSE_SEC_FACULTY_ADDDATE { get; set; }
        public string COURSE_SEC_FACULTY_CHGOPR { get; set; }
        public Nullable<System.DateTime> COURSE_SEC_FACULTY_CHGDATE { get; set; }
        public string CSF_USER1 { get; set; }
        public string CSF_USER2 { get; set; }
        public string CSF_USER3 { get; set; }
        public string CSF_USER4 { get; set; }
        public string CSF_USER5 { get; set; }
        public string CSF_USER6 { get; set; }
        public string CSF_USER7 { get; set; }
        public string CSF_USER8 { get; set; }
        public string CSF_USER9 { get; set; }
        public string CSF_USER10 { get; set; }
        public string CSF_PAC_LP_ASGMT { get; set; }
    
        public virtual COURSE_SECTIONS COURSE_SECTIONS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COURSE_SECTIONS_LS> COURSE_SECTIONS_LS { get; set; }
    }
}
