//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lcapas.Core.Models.Colldb
{
    using System;
    using System.Collections.Generic;
    
    public partial class COURSE_SECTIONS_LS
    {
        public string COURSE_SECTIONS_ID { get; set; }
        public decimal POS { get; set; }
        public string SEC_MEETING { get; set; }
        public string SEC_OTHER_REG_BILLING_RATES { get; set; }
        public string SEC_COURSE_TYPES { get; set; }
        public string SEC_STUDENTS { get; set; }
        public string SEC_COURSE_LEVELS { get; set; }
        public string SEC_FACULTY { get; set; }
        public string SEC_REG_RESTRICTIONS { get; set; }
        public string SEC_SUPPLIES { get; set; }
        public string SEC_DISCOUNTS { get; set; }
        public string SEC_WITHDRAWN_STUDENTS { get; set; }
        public string SEC_ROOM_TYPES { get; set; }
        public string SEC_PREFERRED_PARTITIONS { get; set; }
        public string SEC_ACTIVE_STUDENTS { get; set; }
        public string SEC_COURSE_SEC_BLOCKS { get; set; }
        public Nullable<System.DateTime> SEC_OVR_CENSUS_DATES { get; set; }
        public string SEC_DIVISIONS { get; set; }
        public string SEC_SCHOOLS { get; set; }
        public string SEC_ROOM_CHARS { get; set; }
        public string SEC_CALENDAR_SCHEDULES { get; set; }
        public string SEC_OTHER_RESTRICTIONS { get; set; }
        public string SEC_REG_BILLING_RATES { get; set; }
        public string SEC_LOCAL_GOVT_CODES { get; set; }
        public string SEC_FUNDING_SOURCES { get; set; }
        public string SEC_SCAN_GRADE_STU_CRS_SEC { get; set; }
        public string SEC_CURRICULUM_OFFERINGS { get; set; }
        public string SEC_SECTION_IDX { get; set; }
        public string SEC_SYNONYM_TERM_IDX { get; set; }
        public string SEC_SUBJ_CRS_LEVEL_IDX { get; set; }
        public string SEC_BOOKS { get; set; }
        public string SEC_BOOK_OPTIONS { get; set; }
        public string SEC_SHORT_TITLE_IDX { get; set; }
        public string SEC_COREQ_SECS { get; set; }
        public string SEC_RECOMMENDED_SECS { get; set; }
        public string SEC_REQS { get; set; }
    
        public virtual COURSE_SEC_FACULTY COURSE_SEC_FACULTY { get; set; }
        public virtual COURSE_SECTIONS COURSE_SECTIONS { get; set; }
        public virtual STUDENT_COURSE_SEC STUDENT_COURSE_SEC { get; set; }
        public virtual STUDENT_COURSE_SEC STUDENT_COURSE_SEC1 { get; set; }
        public virtual STUDENT_COURSE_SEC STUDENT_COURSE_SEC2 { get; set; }
        public virtual STUDENT_COURSE_SEC STUDENT_COURSE_SEC3 { get; set; }
    }
}
