//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lcapas.Core.Models.Colldb
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXTERNAL_NOTES
    {
        public string EXTERNAL_TRANSCRIPTS_ID { get; set; }
        public decimal POS { get; set; }
        public string EXTL_NOTES { get; set; }
        public Nullable<System.DateTime> EXTL_NOTE_DATE { get; set; }
    
        public virtual EXTERNAL_TRANSCRIPTS EXTERNAL_TRANSCRIPTS { get; set; }
    }
}
