//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lcapas.Core.Models.Colldb
{
    using System;
    using System.Collections.Generic;
    
    public partial class FOREIGN_PERSON
    {
        public string FOREIGN_PERSON_ID { get; set; }
        public string FPER_ALIEN_STATUS { get; set; }
        public string FOREIGN_PERSON_ADDOPR { get; set; }
        public Nullable<System.DateTime> FOREIGN_PERSON_ADDDATE { get; set; }
        public string FOREIGN_PERSON_CHGOPR { get; set; }
        public Nullable<System.DateTime> FOREIGN_PERSON_CHGDATE { get; set; }
        public string FPER_BIRTH_COUNTRY { get; set; }
        public string FPER_BIRTH_CITY { get; set; }
        public string FPER_VISA_NO { get; set; }
        public string FPER_VISA_ISSUE_COUNTRY { get; set; }
        public string FPER_I94_NO { get; set; }
        public string FPER_PASSPORT_NO { get; set; }
        public string FPER_PASSPORT_COUNTRY { get; set; }
        public Nullable<System.DateTime> FPER_PASSPORT_EXPIRE_DATE { get; set; }
        public string FPER_PORT_OF_ENTRY { get; set; }
        public string FPER_IMMIGRATION_STATUS { get; set; }
        public string FPER_REG_NO { get; set; }
        public string FPER_VISA_ISSUE_POST { get; set; }
        public string FPER_RESIDENCE_COUNTRY { get; set; }
        public string FPER_VISA_TYPE { get; set; }
        public Nullable<System.DateTime> FPER_VISA_ISSUE_DATE { get; set; }
        public Nullable<System.DateTime> FPER_VISA_EXPIRE_DATE { get; set; }
        public Nullable<System.DateTime> FPER_COUNTRY_ENTRY_DATE { get; set; }
        public string FPER_SEVIS_LAST_NAME { get; set; }
        public string FPER_PHONE_EXEMPT_IND { get; set; }
        public string FPER_SEVIS_GIVEN_NAME { get; set; }
        public Nullable<System.DateTime> FPER_VISA_REQUEST_DATE { get; set; }
        public string FPER_ALIEN_REG_NO_EXP { get; set; }
    
        public virtual PEOPLE PERSON { get; set; }
    }
}
