//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lcapas.Core.Models.Colldb
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRADE_SCHEMES_LS
    {
        public string GRADE_SCHEMES_ID { get; set; }
        public decimal POS { get; set; }
        public string GRS_GRADES { get; set; }
    
        public virtual GRADE_SCHEMES GRADE_SCHEMES { get; set; }
        public virtual GRADE GRADE { get; set; }
    }
}
