//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lcapas.Core.Models.Colldb
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRADE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GRADE()
        {
            this.GRADES1 = new HashSet<GRADE>();
            this.GRADES11 = new HashSet<GRADE>();
            this.GRADES12 = new HashSet<GRADE>();
            this.GRADES13 = new HashSet<GRADE>();
            this.GRADES14 = new HashSet<GRADE>();
            this.STUDENT_ACAD_CRED = new HashSet<STUDENT_ACAD_CRED>();
            this.STUDENT_ACAD_CRED1 = new HashSet<STUDENT_ACAD_CRED>();
            this.STUDENT_COURSE_SEC = new HashSet<STUDENT_COURSE_SEC>();
            this.STUDENT_COURSE_SEC1 = new HashSet<STUDENT_COURSE_SEC>();
            this.STUDENT_COURSE_SEC2 = new HashSet<STUDENT_COURSE_SEC>();
            this.STUDENT_COURSE_SEC3 = new HashSet<STUDENT_COURSE_SEC>();
            this.STUDENT_COURSE_SEC4 = new HashSet<STUDENT_COURSE_SEC>();
            this.STUDENT_COURSE_SEC5 = new HashSet<STUDENT_COURSE_SEC>();
            this.EXTERNAL_TRANSCRIPTS = new HashSet<EXTERNAL_TRANSCRIPTS>();
            this.EXTERNAL_TRANSCRIPTS1 = new HashSet<EXTERNAL_TRANSCRIPTS>();
            this.GRADE_SCHEMES_LS = new HashSet<GRADE_SCHEMES_LS>();
            this.STUDENT_NON_COURSES = new HashSet<STUDENT_NON_COURSES>();
        }
    
        public string GRADES_ID { get; set; }
        public Nullable<decimal> GRD_VALUE { get; set; }
        public string GRD_LEGEND { get; set; }
        public string GRD_GRADE_SCHEME { get; set; }
        public string GRD_GRADE { get; set; }
        public string GRD_ATT_CRED_FLAG { get; set; }
        public string GRD_CMPL_CRED_FLAG { get; set; }
        public string GRD_GPA_CRED_FLAG { get; set; }
        public string GRD_REPL_ATT_CRED_FLAG { get; set; }
        public string GRD_REPL_CMPL_CRED_FLAG { get; set; }
        public string GRD_REPL_GPA_CRED_FLAG { get; set; }
        public Nullable<decimal> GRD_REPEAT_VALUE { get; set; }
        public string GRD_PASS_NOPASS_GRADE { get; set; }
        public string GRD_WITHDRAW_GRADE { get; set; }
        public string GRD_AUDIT_GRADE { get; set; }
        public string GRD_INCOMPLETE_GRADE { get; set; }
        public string GRADES_ADDOPR { get; set; }
        public Nullable<System.DateTime> GRADES_ADDDATE { get; set; }
        public string GRADES_CHGOPR { get; set; }
        public Nullable<System.DateTime> GRADES_CHGDATE { get; set; }
        public string GRD_USER1 { get; set; }
        public string GRD_USER2 { get; set; }
        public string GRD_USER3 { get; set; }
        public string GRD_USER4 { get; set; }
        public string GRD_USER5 { get; set; }
        public string GRD_USER6 { get; set; }
        public string GRD_USER7 { get; set; }
        public string GRD_USER8 { get; set; }
        public string GRD_USER9 { get; set; }
        public string GRD_USER10 { get; set; }
        public string GRD_EXCLUDE_FROM_FAC_FLAG { get; set; }
        public string GRD_FINAL_REQUIRE_LDA { get; set; }
        public string GRD_COMPARISON_GRADE { get; set; }
        public string GRD_USE_AFTER_DROP_GRD_REQD { get; set; }
        public string GRD_USE_IN_FINAL_GRD_LIST { get; set; }
        public string GRD_USE_IN_MIDTERM_GRD_LIST { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GRADE> GRADES1 { get; set; }
        public virtual GRADE GRADE1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GRADE> GRADES11 { get; set; }
        public virtual GRADE GRADE2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GRADE> GRADES12 { get; set; }
        public virtual GRADE GRADE3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GRADE> GRADES13 { get; set; }
        public virtual GRADE GRADE4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GRADE> GRADES14 { get; set; }
        public virtual GRADE GRADE5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STUDENT_ACAD_CRED> STUDENT_ACAD_CRED { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STUDENT_ACAD_CRED> STUDENT_ACAD_CRED1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STUDENT_COURSE_SEC> STUDENT_COURSE_SEC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STUDENT_COURSE_SEC> STUDENT_COURSE_SEC1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STUDENT_COURSE_SEC> STUDENT_COURSE_SEC2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STUDENT_COURSE_SEC> STUDENT_COURSE_SEC3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STUDENT_COURSE_SEC> STUDENT_COURSE_SEC4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STUDENT_COURSE_SEC> STUDENT_COURSE_SEC5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EXTERNAL_TRANSCRIPTS> EXTERNAL_TRANSCRIPTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EXTERNAL_TRANSCRIPTS> EXTERNAL_TRANSCRIPTS1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GRADE_SCHEMES_LS> GRADE_SCHEMES_LS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STUDENT_NON_COURSES> STUDENT_NON_COURSES { get; set; }
    }
}
