//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lcapas.Core.Models.Colldb
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRADE_SCHEMES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GRADE_SCHEMES()
        {
            this.COURSE_SECTIONS = new HashSet<COURSE_SECTIONS>();
            this.EXTERNAL_TRANSCRIPTS = new HashSet<EXTERNAL_TRANSCRIPTS>();
            this.GRADE_SCHEMES_LS = new HashSet<GRADE_SCHEMES_LS>();
            this.STUDENT_ACAD_CRED = new HashSet<STUDENT_ACAD_CRED>();
            this.STUDENT_NON_COURSES = new HashSet<STUDENT_NON_COURSES>();
            this.ACAD_PROGRAMS = new HashSet<ACAD_PROGRAMS>();
        }
    
        public string GRADE_SCHEMES_ID { get; set; }
        public string GRS_DESC { get; set; }
        public string GRS_REPEAT_GRADE_USE { get; set; }
        public string GRS_SUBROUTINE { get; set; }
        public Nullable<System.DateTime> GRS_START_DATE { get; set; }
        public Nullable<System.DateTime> GRS_END_DATE { get; set; }
        public string GRADE_SCHEMES_ADDOPR { get; set; }
        public Nullable<System.DateTime> GRADE_SCHEMES_ADDDATE { get; set; }
        public string GRADE_SCHEMES_CHGOPR { get; set; }
        public Nullable<System.DateTime> GRADE_SCHEMES_CHGDATE { get; set; }
        public string GRS_USER1 { get; set; }
        public string GRS_USER2 { get; set; }
        public string GRS_USER3 { get; set; }
        public string GRS_USER4 { get; set; }
        public string GRS_USER5 { get; set; }
        public string GRS_USER6 { get; set; }
        public string GRS_USER7 { get; set; }
        public string GRS_USER8 { get; set; }
        public string GRS_USER9 { get; set; }
        public string GRS_USER10 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COURSE_SECTIONS> COURSE_SECTIONS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EXTERNAL_TRANSCRIPTS> EXTERNAL_TRANSCRIPTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GRADE_SCHEMES_LS> GRADE_SCHEMES_LS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STUDENT_ACAD_CRED> STUDENT_ACAD_CRED { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STUDENT_NON_COURSES> STUDENT_NON_COURSES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACAD_PROGRAMS> ACAD_PROGRAMS { get; set; }
    }
}
