//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lcapas.Core.Models.Colldb
{
    using System;
    using System.Collections.Generic;
    
    public partial class INSTITUTION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INSTITUTION()
        {
            this.APPLICATIONS = new HashSet<APPLICATION>();
            this.EXTERNAL_TRANSCRIPTS = new HashSet<EXTERNAL_TRANSCRIPTS>();
            this.DEPTS = new HashSet<DEPT>();
            this.ACAD_CREDENTIALS = new HashSet<ACAD_CREDENTIALS>();
        }
    
        public string INSTITUTIONS_ID { get; set; }
        public string INST_CEEB { get; set; }
        public string INST_LOCAL_GOVT_ID { get; set; }
        public Nullable<decimal> INST_CRED_CONVERSION { get; set; }
        public string INST_OTHER_ID { get; set; }
        public string INST_TYPE { get; set; }
        public string INST_ACAD_CALENDAR { get; set; }
        public string INST_FUND_BY { get; set; }
        public Nullable<System.DateTime> INSTITUTIONS_ADD_DATE { get; set; }
        public string INSTITUTIONS_ADD_OPERATOR { get; set; }
        public Nullable<System.DateTime> INSTITUTIONS_CHANGE_DATE { get; set; }
        public string INSTITUTIONS_CHANGE_OPERATOR { get; set; }
        public string INST_GRADE_SCHEME { get; set; }
        public string INST_USER1 { get; set; }
        public string INST_USER2 { get; set; }
        public string INST_USER3 { get; set; }
        public string INST_USER4 { get; set; }
        public string INST_USER5 { get; set; }
        public string INST_USER6 { get; set; }
        public string INST_USER7 { get; set; }
        public string INST_USER8 { get; set; }
        public string INST_USER9 { get; set; }
        public string INST_USER10 { get; set; }
        public string INST_USER11 { get; set; }
        public string INST_USER12 { get; set; }
        public string INST_USER13 { get; set; }
        public string INST_USER14 { get; set; }
        public string INST_USER15 { get; set; }
        public string INST_USER16 { get; set; }
        public string INST_USER17 { get; set; }
        public string INST_USER18 { get; set; }
        public string INST_USER19 { get; set; }
        public string INST_USER20 { get; set; }
        public string INST_USER21 { get; set; }
        public string INST_USER22 { get; set; }
        public string INST_USER23 { get; set; }
        public string INST_BOARD_ID { get; set; }
        public Nullable<decimal> INST_CEEB_NUM_IDX { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APPLICATION> APPLICATIONS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EXTERNAL_TRANSCRIPTS> EXTERNAL_TRANSCRIPTS { get; set; }
        public virtual PEOPLE PERSON { get; set; }
        public virtual PEOPLE PERSON1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEPT> DEPTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACAD_CREDENTIALS> ACAD_CREDENTIALS { get; set; }
    }
}
