//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lcapas.Core.Models.Colldb
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAILING
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MAILING()
        {
            this.CH_CORR = new HashSet<CH_CORR>();
        }
    
        public string MAILING_ID { get; set; }
        public string MAILING_SALUTATION { get; set; }
        public Nullable<System.DateTime> MAILING_ADD_DATE { get; set; }
        public string MAILING_ADD_OPERATOR { get; set; }
        public string MAILING_ADDRESS_TYPE { get; set; }
        public string MAILING_RESERVED_21 { get; set; }
        public string MAILING_EMAIL_HIERARCHY { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CH_CORR> CH_CORR { get; set; }
        public virtual PEOPLE PERSON { get; set; }
    }
}
