//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lcapas.Core.Models.Colldb
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSON_ST_LS
    {
        public string PERSON_ST_ID { get; set; }
        public decimal POS { get; set; }
        public string PST_CAMPUS_ORGS_ADVISOR { get; set; }
        public string PST_CAMPUS_ORGS_MEMBER { get; set; }
        public string PST_ROOM_PREFERENCES { get; set; }
        public string PST_ROOM_ASSIGNMENTS { get; set; }
        public string PST_REP_APPLICATIONS { get; set; }
        public string PST_STUDENT_ACAD_CRED { get; set; }
        public string PST_STUDENT_EQUIV_EVALS { get; set; }
        public string PST_STUDENT_NON_COURSES { get; set; }
        public string PST_ADMISSIONS_TESTS { get; set; }
        public string PST_PLACEMENT_TESTS { get; set; }
        public string PST_OTHER_TESTS { get; set; }
        public string PST_MEAL_PLANS { get; set; }
        public string PST_STUDENT_COURSE_SEC { get; set; }
        public string PST_SPONSORSHIPS { get; set; }
        public string PST_COF_STUDENT_ACAD_CRED { get; set; }
        public string PST_EXTERNAL_TRANSCRIPTS { get; set; }
        public string PST_RESTRICTIONS { get; set; }
        public string PST_ADVISEMENT { get; set; }
        public string PST_NAA_ATTENDANCES { get; set; }
        public string PST_NAA_REQMTS { get; set; }
    
        public virtual APPLICATION APPLICATION { get; set; }
        public virtual EXTERNAL_TRANSCRIPTS EXTERNAL_TRANSCRIPTS { get; set; }
        public virtual PEOPLE PERSON { get; set; }
        public virtual PERSON_ST PERSON_ST { get; set; }
        public virtual STUDENT_ACAD_CRED STUDENT_ACAD_CRED { get; set; }
        public virtual STUDENT_ACAD_CRED STUDENT_ACAD_CRED1 { get; set; }
        public virtual STUDENT_COURSE_SEC STUDENT_COURSE_SEC { get; set; }
        public virtual STUDENT_EQUIV_EVALS STUDENT_EQUIV_EVALS { get; set; }
        public virtual STUDENT_RESTRICTIONS STUDENT_RESTRICTIONS { get; set; }
        public virtual STUDENT_NON_COURSES STUDENT_NON_COURSES { get; set; }
        public virtual STUDENT_NON_COURSES STUDENT_NON_COURSES1 { get; set; }
        public virtual STUDENT_NON_COURSES STUDENT_NON_COURSES2 { get; set; }
        public virtual STUDENT_NON_COURSES STUDENT_NON_COURSES3 { get; set; }
    }
}
