//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lcapas.Core.Models.Colldb
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSON_ST
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PERSON_ST()
        {
            this.APPLICATIONS = new HashSet<APPLICATION>();
            this.EXTERNAL_TRANSCRIPTS = new HashSet<EXTERNAL_TRANSCRIPTS>();
            this.PERSON_ST_LS = new HashSet<PERSON_ST_LS>();
            this.STUDENT_ACAD_CRED = new HashSet<STUDENT_ACAD_CRED>();
            this.STUDENT_COURSE_SEC = new HashSet<STUDENT_COURSE_SEC>();
            this.STUDENT_EQUIV_EVALS = new HashSet<STUDENT_EQUIV_EVALS>();
            this.STUDENT_RESTRICTIONS = new HashSet<STUDENT_RESTRICTIONS>();
            this.STUDENT_NON_COURSES = new HashSet<STUDENT_NON_COURSES>();
        }
    
        public string PERSON_ST_ID { get; set; }
        public string PERSON_ST_ADDOPR { get; set; }
        public Nullable<System.DateTime> PERSON_ST_ADDDATE { get; set; }
        public string PERSON_ST_CHGOPR { get; set; }
        public Nullable<System.DateTime> PERSON_ST_CHGDATE { get; set; }
        public Nullable<decimal> PST_FA_REG_CRED { get; set; }
        public string PST_FA_REG_CRED_AWARD_PERIOD { get; set; }
        public Nullable<decimal> PST_FA_INST_REG_CRED { get; set; }
        public string PST_VISITING_FROM_INST { get; set; }
        public string PST_VISITING_STUDENT { get; set; }
        public Nullable<System.DateTime> PST_VISITING_STUDENT_DATE { get; set; }
        public Nullable<decimal> PST_FA_DL_REG_CRED { get; set; }
        public Nullable<decimal> PST_FA_PELL_REG_CRED { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APPLICATION> APPLICATIONS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EXTERNAL_TRANSCRIPTS> EXTERNAL_TRANSCRIPTS { get; set; }
        public virtual PEOPLE PERSON { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PERSON_ST_LS> PERSON_ST_LS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STUDENT_ACAD_CRED> STUDENT_ACAD_CRED { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STUDENT_COURSE_SEC> STUDENT_COURSE_SEC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STUDENT_EQUIV_EVALS> STUDENT_EQUIV_EVALS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STUDENT_RESTRICTIONS> STUDENT_RESTRICTIONS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STUDENT_NON_COURSES> STUDENT_NON_COURSES { get; set; }
    }
}
