//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lcapas.Core.Models.Colldb
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESTRICTIONS_LS
    {
        public string RESTRICTIONS_ID { get; set; }
        public decimal POS { get; set; }
        public string REST_OFFICE_CODES { get; set; }
    
        public virtual RESTRICTION RESTRICTION { get; set; }
        public virtual RESTRICTION RESTRICTION1 { get; set; }
    }
}
