//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lcapas.Core.Models.Colldb
{
    using System;
    using System.Collections.Generic;
    
    public partial class RULES_CHECK
    {
        public string RULES_ID { get; set; }
        public decimal POS { get; set; }
        public string RL_CHECK_DATA_ELEMENTS { get; set; }
        public string RL_CHECK_OPERATORS { get; set; }
        public string RL_CHECK_VALUES { get; set; }
        public string RL_CHECK_DATA_USING { get; set; }
        public string RL_CHECK_DATA_WHEN { get; set; }
        public string RL_CHECK_DATA_WHEN_OPER { get; set; }
        public string RL_CHECK_DATA_WHEN_VALUE { get; set; }
        public string RL_CHECK_VALUE_USING { get; set; }
        public string RL_CHECK_VALUE_WHEN { get; set; }
        public string RL_CHECK_VALUE_WHEN_OPER { get; set; }
        public string RL_CHECK_VALUE_WHEN_VALUE { get; set; }
        public string RL_CHECK_CONNECTOR { get; set; }
        public string RL_CHECK_FAILURE_MSG { get; set; }
    }
}
