//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lcapas.Core.Models.Colldb
{
    using System;
    using System.Collections.Generic;
    
    public partial class STC_STATUSES
    {
        public string STUDENT_ACAD_CRED_ID { get; set; }
        public decimal POS { get; set; }
        public Nullable<System.DateTime> STC_STATUS_TIME { get; set; }
        public string STC_STATUS { get; set; }
        public Nullable<System.DateTime> STC_STATUS_DATE { get; set; }
        public string STC_STATUS_REASON { get; set; }
    
        public virtual STUDENT_ACAD_CRED STUDENT_ACAD_CRED { get; set; }
    }
}
