//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lcapas.Core.Models.Colldb
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT_COURSE_SEC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public STUDENT_COURSE_SEC()
        {
            this.STUDENT_ACAD_CRED = new HashSet<STUDENT_ACAD_CRED>();
            this.PERSON_ST_LS = new HashSet<PERSON_ST_LS>();
            this.COURSE_SECTIONS_LS = new HashSet<COURSE_SECTIONS_LS>();
            this.COURSE_SECTIONS_LS1 = new HashSet<COURSE_SECTIONS_LS>();
            this.COURSE_SECTIONS_LS2 = new HashSet<COURSE_SECTIONS_LS>();
            this.COURSE_SECTIONS_LS3 = new HashSet<COURSE_SECTIONS_LS>();
        }
    
        public string STUDENT_COURSE_SEC_ID { get; set; }
        public string SCS_COURSE_SECTION { get; set; }
        public string SCS_STUDENT { get; set; }
        public Nullable<decimal> SCS_OVERRIDE_BILLING_CRED { get; set; }
        public string SCS_PASS_AUDIT { get; set; }
        public Nullable<System.DateTime> SCS_ABSENT_NOTICE_DATE { get; set; }
        public string SCS_REG_METHOD { get; set; }
        public Nullable<decimal> SCS_RANDOM_ID { get; set; }
        public string SCS_LOCATION { get; set; }
        public string SCS_STUDENT_ACAD_CRED { get; set; }
        public string SCS_MID_TERM_GRADE1 { get; set; }
        public Nullable<System.DateTime> SCS_MID_GRADE_DATE1 { get; set; }
        public Nullable<System.DateTime> STUDENT_COURSE_SEC_CHGDATE { get; set; }
        public string STUDENT_COURSE_SEC_CHGOPR { get; set; }
        public Nullable<decimal> SCS_ATTENDANCE_HOURS { get; set; }
        public Nullable<System.DateTime> SCS_LAST_ATTEND_DATE { get; set; }
        public string SCS_AR_POSTED_FLAG { get; set; }
        public string SCS_COMMENTS { get; set; }
        public string SCS_PRINTED_COMMENTS { get; set; }
        public string SCS_MID_TERM_GRADE2 { get; set; }
        public Nullable<System.DateTime> SCS_MID_GRADE_DATE2 { get; set; }
        public string SCS_MID_TERM_GRADE3 { get; set; }
        public Nullable<System.DateTime> SCS_MID_GRADE_DATE3 { get; set; }
        public string SCS_MID_TERM_GRADE4 { get; set; }
        public Nullable<System.DateTime> SCS_MID_GRADE_DATE4 { get; set; }
        public string SCS_MID_TERM_GRADE5 { get; set; }
        public Nullable<System.DateTime> SCS_MID_GRADE_DATE5 { get; set; }
        public string SCS_MID_TERM_GRADE6 { get; set; }
        public Nullable<System.DateTime> SCS_MID_GRADE_DATE6 { get; set; }
        public string SCS_REG_TIME_PERIOD { get; set; }
        public Nullable<System.DateTime> STUDENT_COURSE_SEC_ADDDATE { get; set; }
        public string STUDENT_COURSE_SEC_ADDOPR { get; set; }
        public string SCS_MID_GRADE_REPORT_FLAG1 { get; set; }
        public string SCS_MID_GRADE_REPORT_FLAG2 { get; set; }
        public string SCS_MID_GRADE_REPORT_FLAG3 { get; set; }
        public string SCS_MID_GRADE_REPORT_FLAG4 { get; set; }
        public string SCS_MID_GRADE_REPORT_FLAG5 { get; set; }
        public string SCS_MID_GRADE_REPORT_FLAG6 { get; set; }
        public string SCS_USER1 { get; set; }
        public string SCS_USER2 { get; set; }
        public string SCS_USER3 { get; set; }
        public string SCS_USER4 { get; set; }
        public string SCS_USER5 { get; set; }
        public string SCS_USER6 { get; set; }
        public string SCS_USER7 { get; set; }
        public string SCS_USER8 { get; set; }
        public string SCS_USER9 { get; set; }
        public string SCS_USER10 { get; set; }
        public string SCS_STUDENTCOURSESECTION_IDX { get; set; }
        public string SCS_MARKETING_SOURCE { get; set; }
        public string SCS_REG_REASON { get; set; }
        public string SCS_NEVER_ATTENDED_FLAG { get; set; }
        public string SCS_LAST_ATTEND_SOURCE { get; set; }
        public string SCS_GB_SORT_CODE { get; set; }
        public string SCS_GRADE_IMPORT_MSGS { get; set; }
        public string SCS_VET_CERT { get; set; }
        public Nullable<System.DateTime> SCS_VET_CERT_DATE { get; set; }
        public string SCS_VET_CERT_PROGRAM { get; set; }
    
        public virtual COURSE_SECTIONS COURSE_SECTIONS { get; set; }
        public virtual GRADE GRADE { get; set; }
        public virtual GRADE GRADE1 { get; set; }
        public virtual GRADE GRADE2 { get; set; }
        public virtual GRADE GRADE3 { get; set; }
        public virtual GRADE GRADE4 { get; set; }
        public virtual GRADE GRADES { get; set; }
        public virtual PEOPLE PERSON { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STUDENT_ACAD_CRED> STUDENT_ACAD_CRED { get; set; }
        public virtual STUDENT_ACAD_CRED STUDENT_ACAD_CRED1 { get; set; }
        public virtual PERSON_ST PERSON_ST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PERSON_ST_LS> PERSON_ST_LS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COURSE_SECTIONS_LS> COURSE_SECTIONS_LS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COURSE_SECTIONS_LS> COURSE_SECTIONS_LS1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COURSE_SECTIONS_LS> COURSE_SECTIONS_LS2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COURSE_SECTIONS_LS> COURSE_SECTIONS_LS3 { get; set; }
    }
}
