//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lcapas.Core.Models.Colldb
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT_REQUEST_LOGS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public STUDENT_REQUEST_LOGS()
        {
            this.STUDENT_REQUEST_LOGS_LS = new HashSet<STUDENT_REQUEST_LOGS_LS>();
        }
    
        public string STUDENT_REQUEST_LOGS_ID { get; set; }
        public string STRL_STUDENT { get; set; }
        public string STRL_RECIPIENT { get; set; }
        public string STRL_TYPE { get; set; }
        public Nullable<System.DateTime> STRL_DATE { get; set; }
        public string STRL_DOCUMENT_CODE { get; set; }
        public Nullable<decimal> STRL_CHARGED_COPIES { get; set; }
        public string STRL_INVOICE { get; set; }
        public string STRL_ADDRESS_ID { get; set; }
        public Nullable<System.DateTime> STRL_PRINT_DATE { get; set; }
        public Nullable<decimal> STRL_COPIES { get; set; }
        public string STRL_ADDRESS_MODIFIER { get; set; }
        public string STRL_CITY { get; set; }
        public string STRL_STATE { get; set; }
        public string STRL_ZIP { get; set; }
        public string STRL_COUNTRY { get; set; }
        public Nullable<System.DateTime> STRL_RECIPIENT_RECD_DATE { get; set; }
        public string STRL_COMMENTS { get; set; }
        public Nullable<System.DateTime> STUDENT_REQUEST_LOGS_ADDDATE { get; set; }
        public string STUDENT_REQUEST_LOGS_ADDOPR { get; set; }
        public Nullable<System.DateTime> STUDENT_REQUEST_LOGS_CHGDATE { get; set; }
        public string STUDENT_REQUEST_LOGS_CHGOPR { get; set; }
        public string STRL_USER1 { get; set; }
        public string STRL_USER2 { get; set; }
        public string STRL_USER3 { get; set; }
        public string STRL_USER4 { get; set; }
        public string STRL_USER5 { get; set; }
        public string STRL_USER6 { get; set; }
        public string STRL_USER7 { get; set; }
        public string STRL_USER8 { get; set; }
        public string STRL_USER9 { get; set; }
        public string STRL_USER10 { get; set; }
        public string STRL_SEND_CODE { get; set; }
        public string STRL_DELIVERY_METHOD { get; set; }
        public Nullable<System.DateTime> STRL_ACKNOWLEDGE_DATE { get; set; }
        public string STRL_TRO_ATTRIBUTES { get; set; }
        public string STRL_RECIPIENT_NAME { get; set; }
        public string STRL_STU_REQUEST_LOG_HOLDS { get; set; }
    
        public virtual ADDRESSES ADDRESS { get; set; }
        public virtual PEOPLE PERSON { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STUDENT_REQUEST_LOGS_LS> STUDENT_REQUEST_LOGS_LS { get; set; }
    }
}
