//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lcapas.Core.Models.Colldb
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT_PROGRAMS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public STUDENT_PROGRAMS()
        {
            this.STPR_DATES = new HashSet<STPR_DATES>();
            this.STPR_STATUSES = new HashSet<STPR_STATUSES>();
        }
    
        public string STUDENT_PROGRAMS_ID { get; set; }
        public Nullable<System.DateTime> STPR_ANT_CMPL_DATE { get; set; }
        public string STPR_CATALOG { get; set; }
        public string STPR_LOCATION { get; set; }
        public string STPR_ADMIT_STATUS { get; set; }
        public string STPR_TITLE { get; set; }
        public string STPR_DEPT { get; set; }
        public string STPR_DIVISION { get; set; }
        public string STPR_SCHOOL { get; set; }
        public string STPR_COMMENTS { get; set; }
        public string STUDENT_PROGRAMS_ADDOPR { get; set; }
        public Nullable<System.DateTime> STUDENT_PROGRAMS_ADDDATE { get; set; }
        public string STUDENT_PROGRAMS_CHGOPR { get; set; }
        public Nullable<System.DateTime> STUDENT_PROGRAMS_CHGDATE { get; set; }
        public string STPR_HONORS_CODE { get; set; }
        public string STPR_EVAL_INCLUDE_CODE { get; set; }
        public string STPR_PRINTED_COMMENTS { get; set; }
        public Nullable<System.DateTime> STPR_EVAL_DATE { get; set; }
        public string STPR_EVAL_STATUS { get; set; }
        public Nullable<decimal> STPR_EVAL_COMBINED_CRED { get; set; }
        public Nullable<decimal> STPR_EVAL_COMBINED_GPA { get; set; }
        public Nullable<decimal> STPR_EVAL_INSTITUTION_CRED { get; set; }
        public Nullable<decimal> STPR_EVAL_INSTITUTION_GPA { get; set; }
        public Nullable<System.DateTime> STPR_EVAL_ACAD_CRED_END_DATE { get; set; }
        public string STPR_USER1 { get; set; }
        public string STPR_USER2 { get; set; }
        public string STPR_USER3 { get; set; }
        public string STPR_USER4 { get; set; }
        public string STPR_USER5 { get; set; }
        public string STPR_USER6 { get; set; }
        public string STPR_USER7 { get; set; }
        public string STPR_USER8 { get; set; }
        public string STPR_USER9 { get; set; }
        public string STPR_USER10 { get; set; }
        public string STPR_STU_PGM_IDX { get; set; }
        public string STPR_STUDENT_ED_PLAN { get; set; }
        public string STPR_INTG_START_TERM { get; set; }
        public string STPR_INTG_ANT_CMPL_TERM { get; set; }
        public string STPR_GRAD_APP_OVERRIDE_FLAG { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STPR_DATES> STPR_DATES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STPR_STATUSES> STPR_STATUSES { get; set; }
        public virtual TERM TERM { get; set; }
        public virtual TERM TERM1 { get; set; }
        public virtual DEPT DEPT { get; set; }
    }
}
