//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lcapas.Core.Models.Colldb
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT_RESTRICTIONS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public STUDENT_RESTRICTIONS()
        {
            this.PERSON_ST_LS = new HashSet<PERSON_ST_LS>();
        }
    
        public string STUDENT_RESTRICTIONS_ID { get; set; }
        public string STR_STUDENT { get; set; }
        public string STR_RESTRICTION { get; set; }
        public Nullable<System.DateTime> STR_START_DATE { get; set; }
        public Nullable<System.DateTime> STR_END_DATE { get; set; }
        public Nullable<decimal> STR_SEVERITY { get; set; }
        public Nullable<System.DateTime> STUDENT_RESTRICTIONS_ADDDATE { get; set; }
        public string STUDENT_RESTRICTIONS_ADDOPR { get; set; }
        public Nullable<System.DateTime> STUDENT_RESTRICTIONS_CHGDATE { get; set; }
        public string STUDENT_RESTRICTIONS_CHGOPR { get; set; }
        public string STR_END_DATE_CHGOPR { get; set; }
        public string STR_COMMENTS { get; set; }
        public string STR_USER1 { get; set; }
        public string STR_USER2 { get; set; }
        public string STR_USER3 { get; set; }
        public string STR_USER4 { get; set; }
        public string STR_USER5 { get; set; }
        public string STR_USER6 { get; set; }
        public string STR_USER7 { get; set; }
        public string STR_USER8 { get; set; }
        public string STR_USER9 { get; set; }
        public string STR_USER10 { get; set; }
        public string STR_PRTL_DISPLAY_FLAG { get; set; }
    
        public virtual PERSON_ST PERSON_ST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PERSON_ST_LS> PERSON_ST_LS { get; set; }
        public virtual RESTRICTION RESTRICTION { get; set; }
    }
}
