//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lcapas.Core.Models.Colldb
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT_STANDINGS
    {
        public string STUDENT_STANDINGS_ID { get; set; }
        public string STS_STUDENT { get; set; }
        public string STS_TYPE { get; set; }
        public string STS_CALC_ACAD_STANDING { get; set; }
        public Nullable<System.DateTime> STUDENT_STANDINGS_ADDDATE { get; set; }
        public string STS_ACAD_STANDING { get; set; }
        public Nullable<System.DateTime> STS_ACAD_STANDING_DATE { get; set; }
        public string STS_OVERRIDE_REASON { get; set; }
        public string STS_TERM { get; set; }
        public string STS_ACAD_PROGRAM { get; set; }
        public string STS_ACAD_LEVEL { get; set; }
        public string STUDENT_STANDINGS_ADDOPR { get; set; }
        public string STUDENT_STANDINGS_CHGOPR { get; set; }
        public Nullable<System.DateTime> STUDENT_STANDINGS_CHGDATE { get; set; }
        public string STS_USER1 { get; set; }
        public string STS_USER2 { get; set; }
        public string STS_USER3 { get; set; }
        public string STS_USER4 { get; set; }
        public string STS_USER5 { get; set; }
        public string STS_USER6 { get; set; }
        public string STS_USER7 { get; set; }
        public string STS_USER8 { get; set; }
        public string STS_USER9 { get; set; }
        public string STS_USER10 { get; set; }
    
        public virtual PEOPLE PERSON { get; set; }
        public virtual TERM TERM { get; set; }
    }
}
