//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lcapas.Core.Models.Colldb
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT_ACAD_CRED_LS
    {
        public string STUDENT_ACAD_CRED_ID { get; set; }
        public decimal POS { get; set; }
        public string STC_DEPTS { get; set; }
        public string STC_DIVISIONS { get; set; }
        public string STC_SCHOOLS { get; set; }
        public Nullable<System.DateTime> STC_GRADE_REPORT_DATES { get; set; }
        public string STC_REPEATED_ACAD_CRED { get; set; }
        public string STC_MARK_ACAD_CREDENTIALS { get; set; }
    
        public virtual STUDENT_ACAD_CRED STUDENT_ACAD_CRED { get; set; }
        public virtual STUDENT_ACAD_CRED STUDENT_ACAD_CRED1 { get; set; }
        public virtual DEPT DEPT { get; set; }
        public virtual ACAD_CREDENTIALS ACAD_CREDENTIALS { get; set; }
    }
}
