//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lcapas.Core.Models.Colldb
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT_TERMS
    {
        public string STUDENT_TERMS_ID { get; set; }
        public string STTR_STUDENT_LOAD { get; set; }
        public Nullable<System.DateTime> STTR_REG_DATE { get; set; }
        public Nullable<System.DateTime> STTR_PREREG_DATE { get; set; }
        public Nullable<decimal> STTR_REG_LOTTERY_NO { get; set; }
        public string STTR_COMMENTS { get; set; }
        public Nullable<decimal> STTR_RANDOM_ID { get; set; }
        public string STTR_PRINTED_COMMENTS { get; set; }
        public string STUDENT_TERMS_ADDOPR { get; set; }
        public Nullable<System.DateTime> STUDENT_TERMS_ADDDATE { get; set; }
        public string STUDENT_TERMS_CHGOPR { get; set; }
        public Nullable<System.DateTime> STUDENT_TERMS_CHGDATE { get; set; }
        public string STTR_CRED_LIMIT_WAIVE_FLAG { get; set; }
        public string STTR_GAIN_STATUS { get; set; }
        public string STTR_REHAB_DEPT_CLIENT_FLAG { get; set; }
        public string STTR_TECH_PREP_FLAG { get; set; }
        public string STTR_USER1 { get; set; }
        public string STTR_USER2 { get; set; }
        public string STTR_USER3 { get; set; }
        public string STTR_USER4 { get; set; }
        public string STTR_USER5 { get; set; }
        public string STTR_USER6 { get; set; }
        public string STTR_USER7 { get; set; }
        public string STTR_USER8 { get; set; }
        public string STTR_USER9 { get; set; }
        public string STTR_USER10 { get; set; }
        public string STTR_USER11 { get; set; }
        public string STTR_USER12 { get; set; }
        public string STTR_USER13 { get; set; }
        public string STTR_USER14 { get; set; }
        public string STTR_USER15 { get; set; }
        public string STTR_USER16 { get; set; }
        public string STTR_USER17 { get; set; }
        public string STTR_USER18 { get; set; }
        public string STTR_USER19 { get; set; }
        public string STTR_USER20 { get; set; }
        public string STTR_USER21 { get; set; }
        public string STTR_USER22 { get; set; }
        public string STTR_USER23 { get; set; }
        public string STTR_USER24 { get; set; }
        public string STTR_USER25 { get; set; }
        public string STTR_USER26 { get; set; }
        public string STTR_USER27 { get; set; }
        public string STTR_USER28 { get; set; }
        public string STTR_USER29 { get; set; }
        public string STTR_USER30 { get; set; }
        public string STTR_USER31 { get; set; }
        public string STTR_USER32 { get; set; }
        public string STTR_USER33 { get; set; }
        public string STTR_USER34 { get; set; }
        public string STTR_USER35 { get; set; }
        public string STTR_USER36 { get; set; }
        public string STTR_USER38 { get; set; }
        public string STTR_USER39 { get; set; }
        public string STTR_USER40 { get; set; }
        public string STTR_USER41 { get; set; }
        public string STTR_USER42 { get; set; }
        public string STTR_USER43 { get; set; }
        public string STTR_USER44 { get; set; }
        public string STTR_USER45 { get; set; }
        public string STTR_USER46 { get; set; }
        public string STTR_USER47 { get; set; }
        public string STTR_USER48 { get; set; }
        public string STTR_USER49 { get; set; }
        public string STTR_USER50 { get; set; }
        public string STTR_USER51 { get; set; }
        public string STTR_USER52 { get; set; }
        public string STTR_USER53 { get; set; }
        public string STTR_USER54 { get; set; }
        public string STTR_USER55 { get; set; }
        public string STTR_USER56 { get; set; }
        public string STTR_USER57 { get; set; }
        public string STTR_USER58 { get; set; }
        public string STTR_USER59 { get; set; }
        public string STTR_USER60 { get; set; }
        public string STTR_USER61 { get; set; }
        public string STTR_USER62 { get; set; }
        public string STTR_USER63 { get; set; }
        public string STTR_USER64 { get; set; }
        public string STTR_USER65 { get; set; }
        public string STTR_USER66 { get; set; }
        public string STTR_USER67 { get; set; }
        public string STTR_JTPA_PARTICIPANT_FLAG { get; set; }
        public string STTR_CALWORKS_STATUS { get; set; }
        public string STTR_CAST_SB11 { get; set; }
        public string STTR_CAST_SB15 { get; set; }
        public Nullable<decimal> STTR_VET_NET_AMT_CERTIFIED { get; set; }
        public Nullable<System.DateTime> STTR_VET_NET_CERTIFIED_DATE { get; set; }
    }
}
