//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lcapas.Core.Models.Colldb
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT_ACAD_CRED
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public STUDENT_ACAD_CRED()
        {
            this.STC_STATUSES = new HashSet<STC_STATUSES>();
            this.STUDENT_COURSE_SEC1 = new HashSet<STUDENT_COURSE_SEC>();
            this.PERSON_ST_LS = new HashSet<PERSON_ST_LS>();
            this.PERSON_ST_LS1 = new HashSet<PERSON_ST_LS>();
            this.STUDENT_EQUIV_EVALS_LS = new HashSet<STUDENT_EQUIV_EVALS_LS>();
            this.STUDENT_EQUIV_EVALS_LS1 = new HashSet<STUDENT_EQUIV_EVALS_LS>();
            this.STUDENT_EQUIV_EVALS_LS2 = new HashSet<STUDENT_EQUIV_EVALS_LS>();
            this.STUDENT_ACAD_CRED_LS = new HashSet<STUDENT_ACAD_CRED_LS>();
            this.STUDENT_ACAD_CRED_LS1 = new HashSet<STUDENT_ACAD_CRED_LS>();
        }
    
        public string STUDENT_ACAD_CRED_ID { get; set; }
        public string STC_PERSON_ID { get; set; }
        public string STC_TITLE { get; set; }
        public string STC_ACAD_LEVEL { get; set; }
        public string STC_COURSE_LEVEL { get; set; }
        public string STC_SUBJECT { get; set; }
        public string STC_COURSE { get; set; }
        public Nullable<decimal> STC_CRED { get; set; }
        public Nullable<decimal> STC_CMPL_CRED { get; set; }
        public Nullable<decimal> STC_GPA_CRED { get; set; }
        public string STC_CRED_TYPE { get; set; }
        public string STC_GRADE_SCHEME { get; set; }
        public string STC_FINAL_GRADE { get; set; }
        public string STC_VERIFIED_GRADE { get; set; }
        public Nullable<System.DateTime> STC_VERIFIED_GRADE_DATE { get; set; }
        public string STC_VERIFIED_GRADE_CHGOPR { get; set; }
        public Nullable<decimal> STC_CEUS { get; set; }
        public string STC_COURSE_NAME { get; set; }
        public string STC_TERM { get; set; }
        public string STC_STUDENT_COURSE_SEC { get; set; }
        public string STC_STUDENT_EQUIV_EVAL { get; set; }
        public Nullable<System.DateTime> STC_GRADE_EXPIRE_DATE { get; set; }
        public Nullable<System.DateTime> STC_START_DATE { get; set; }
        public Nullable<System.DateTime> STC_END_DATE { get; set; }
        public string STC_PRINTED_COMMENTS { get; set; }
        public string STC_COMMENTS { get; set; }
        public string STC_GRADE_REPORT_FLAG { get; set; }
        public Nullable<decimal> STC_ATT_CEUS { get; set; }
        public Nullable<decimal> STC_CMPL_CEUS { get; set; }
        public Nullable<decimal> STC_ATT_CRED { get; set; }
        public Nullable<decimal> STC_CRED_CONVERSION { get; set; }
        public Nullable<decimal> STC_CUM_CONTRIB_ATT_CRED { get; set; }
        public Nullable<decimal> STC_CUM_CONTRIB_CMPL_CRED { get; set; }
        public Nullable<decimal> STC_CUM_CONTRIB_GPA_CRED { get; set; }
        public Nullable<decimal> STC_ALTCUM_CONTRIB_ATT_CRED { get; set; }
        public Nullable<decimal> STC_ALTCUM_CONTRIB_CMPL_CRED { get; set; }
        public Nullable<decimal> STC_ALTCUM_CONTRIB_GPA_CRED { get; set; }
        public Nullable<decimal> STC_GRADE_PTS { get; set; }
        public Nullable<decimal> STC_CUM_CONTRIB_GRADE_PTS { get; set; }
        public Nullable<decimal> STC_ALTCUM_CONTRIB_GRADE_PTS { get; set; }
        public string STC_REPL_CODE { get; set; }
        public string STUDENT_ACAD_CRED_ADDOPR { get; set; }
        public Nullable<System.DateTime> STUDENT_ACAD_CRED_ADDDATE { get; set; }
        public string STUDENT_ACAD_CRED_CHGOPR { get; set; }
        public Nullable<System.DateTime> STUDENT_ACAD_CRED_CHGDATE { get; set; }
        public string STC_ALLOW_REPL_FLAG { get; set; }
        public string STC_SECTION_NO { get; set; }
        public string STC_MARK { get; set; }
        public Nullable<System.DateTime> STC_MARK_DATE { get; set; }
        public string STC_USER1 { get; set; }
        public string STC_USER2 { get; set; }
        public string STC_USER3 { get; set; }
        public string STC_USER4 { get; set; }
        public string STC_USER5 { get; set; }
        public string STC_USER6 { get; set; }
        public string STC_USER7 { get; set; }
        public string STC_USER8 { get; set; }
        public string STC_USER9 { get; set; }
        public string STC_USER10 { get; set; }
        public string STC_MANUAL_CRED_INDIC { get; set; }
        public string STC_REPORTING_TERM { get; set; }
        public string STC_STUDENT_COURSE_IDX { get; set; }
        public string STC_FINAL_GRADE_LOCK_STATUS { get; set; }
        public Nullable<System.DateTime> STC_FINAL_GRADE_LOCK_DATE { get; set; }
        public string STC_FINAL_GRADE_LOCK_OPR { get; set; }
        public string STC_GRADE_IMPORT_MSGS { get; set; }
        public string STC_FA_OVERRIDE { get; set; }
        public string STC_INTG_KEY_IDX { get; set; }
        public string STC_INT_TO_WD { get; set; }
        public Nullable<System.DateTime> STC_INT_TO_WD_DATE { get; set; }
        public Nullable<System.DateTime> STC_INT_TO_WD_TIME { get; set; }
        public string STC_INT_TO_WD_USER { get; set; }
    
        public virtual GRADE GRADE { get; set; }
        public virtual GRADE GRADE1 { get; set; }
        public virtual PEOPLE PERSON { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STC_STATUSES> STC_STATUSES { get; set; }
        public virtual STUDENT_COURSE_SEC STUDENT_COURSE_SEC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STUDENT_COURSE_SEC> STUDENT_COURSE_SEC1 { get; set; }
        public virtual GRADE_SCHEMES GRADE_SCHEMES { get; set; }
        public virtual PERSON_ST PERSON_ST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PERSON_ST_LS> PERSON_ST_LS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PERSON_ST_LS> PERSON_ST_LS1 { get; set; }
        public virtual STUDENT_EQUIV_EVALS STUDENT_EQUIV_EVALS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STUDENT_EQUIV_EVALS_LS> STUDENT_EQUIV_EVALS_LS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STUDENT_EQUIV_EVALS_LS> STUDENT_EQUIV_EVALS_LS1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STUDENT_EQUIV_EVALS_LS> STUDENT_EQUIV_EVALS_LS2 { get; set; }
        public virtual TERM TERM { get; set; }
        public virtual TERM TERM1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STUDENT_ACAD_CRED_LS> STUDENT_ACAD_CRED_LS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STUDENT_ACAD_CRED_LS> STUDENT_ACAD_CRED_LS1 { get; set; }
    }
}
