//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lcapas.Core.Models.Colldb
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT_REQUEST_LOGS_LS
    {
        public string STUDENT_REQUEST_LOGS_ID { get; set; }
        public decimal POS { get; set; }
        public string STRL_TRANSCRIPT_GROUPINGS { get; set; }
        public string STRL_ADDRESS { get; set; }
    
        public virtual STUDENT_REQUEST_LOGS STUDENT_REQUEST_LOGS { get; set; }
    }
}
