//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lcapas.Core.Models.Colldb
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT_NON_COURSES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public STUDENT_NON_COURSES()
        {
            this.PERSON_ST_LS = new HashSet<PERSON_ST_LS>();
            this.PERSON_ST_LS1 = new HashSet<PERSON_ST_LS>();
            this.PERSON_ST_LS2 = new HashSet<PERSON_ST_LS>();
            this.PERSON_ST_LS3 = new HashSet<PERSON_ST_LS>();
            this.STUDENT_EQUIV_EVALS = new HashSet<STUDENT_EQUIV_EVALS>();
        }
    
        public string STUDENT_NON_COURSES_ID { get; set; }
        public string STNC_PERSON_ID { get; set; }
        public string STNC_LICENSING_STATE { get; set; }
        public string STNC_LICENSING_COUNTY { get; set; }
        public Nullable<decimal> STNC_SCORE { get; set; }
        public Nullable<decimal> STNC_PCT { get; set; }
        public string STNC_SOURCE { get; set; }
        public string STNC_INSTITUTION { get; set; }
        public string STNC_TEST_FORM_NAME { get; set; }
        public string STNC_TEST_FORM_NO { get; set; }
        public string STNC_CATEGORY { get; set; }
        public string STNC_TITLE { get; set; }
        public string STNC_COMMENTS { get; set; }
        public Nullable<System.DateTime> STUDENT_NON_COURSES_ADDDATE { get; set; }
        public string STUDENT_NON_COURSES_ADDOPR { get; set; }
        public Nullable<System.DateTime> STUDENT_NON_COURSES_CHGDATE { get; set; }
        public string STUDENT_NON_COURSES_CHGOPR { get; set; }
        public string STNC_INDEX { get; set; }
        public string STNC_LICENSING_COUNTRY { get; set; }
        public string STNC_STUDENT_EQUIV_EVAL { get; set; }
        public Nullable<System.DateTime> STNC_START_DATE { get; set; }
        public Nullable<System.DateTime> STNC_END_DATE { get; set; }
        public string STNC_GRADE_SCHEME { get; set; }
        public string STNC_GRADE { get; set; }
        public string STNC_STATUS { get; set; }
        public Nullable<System.DateTime> STNC_STATUS_DATE { get; set; }
        public string STNC_NON_COURSE { get; set; }
        public string STNC_USER1 { get; set; }
        public string STNC_USER2 { get; set; }
        public string STNC_USER3 { get; set; }
        public string STNC_USER4 { get; set; }
        public string STNC_USER5 { get; set; }
        public string STNC_USER6 { get; set; }
        public string STNC_USER7 { get; set; }
        public string STNC_USER8 { get; set; }
        public string STNC_USER9 { get; set; }
        public string STNC_USER10 { get; set; }
        public string STNC_PERSON_NON_CRS_IDX { get; set; }
        public string STNC_TEST_TYPE { get; set; }
        public string STNC_CUSTOM_FIELDS_XML { get; set; }
        public Nullable<decimal> STNC_PCT2 { get; set; }
        public Nullable<decimal> STNC_SCORE_DEC { get; set; }
        public string STNC_STU_ED_FUNC_LEVEL { get; set; }
        public Nullable<System.DateTime> STNC_STU_ED_FUNC_LEVEL_DATE { get; set; }
        public string STNC_TEST_OTHER_TYPE { get; set; }
    
        public virtual GRADE_SCHEMES GRADE_SCHEMES { get; set; }
        public virtual GRADE GRADE { get; set; }
        public virtual PEOPLE PERSON { get; set; }
        public virtual PERSON_ST PERSON_ST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PERSON_ST_LS> PERSON_ST_LS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PERSON_ST_LS> PERSON_ST_LS1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PERSON_ST_LS> PERSON_ST_LS2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PERSON_ST_LS> PERSON_ST_LS3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STUDENT_EQUIV_EVALS> STUDENT_EQUIV_EVALS { get; set; }
        public virtual STUDENT_EQUIV_EVALS STUDENT_EQUIV_EVALS1 { get; set; }
    }
}
