//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lcapas.Core.Models.Colldb
{
    using System;
    using System.Collections.Generic;
    
    public partial class TERM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TERM()
        {
            this.APPLICATIONS = new HashSet<APPLICATION>();
            this.COURSE_SECTIONS = new HashSet<COURSE_SECTIONS>();
            this.STUDENT_ACAD_CRED = new HashSet<STUDENT_ACAD_CRED>();
            this.STUDENT_ACAD_CRED1 = new HashSet<STUDENT_ACAD_CRED>();
            this.STUDENT_STANDINGS = new HashSet<STUDENT_STANDINGS>();
            this.STUDENT_PROGRAMS = new HashSet<STUDENT_PROGRAMS>();
            this.STUDENT_PROGRAMS1 = new HashSet<STUDENT_PROGRAMS>();
        }
    
        public string TERMS_ID { get; set; }
        public Nullable<decimal> TERM_REPORTING_YEAR { get; set; }
        public string TERM_DESC { get; set; }
        public Nullable<System.DateTime> TERM_PREREG_START_DATE { get; set; }
        public Nullable<System.DateTime> TERM_REG_START_DATE { get; set; }
        public Nullable<System.DateTime> TERM_START_DATE { get; set; }
        public Nullable<System.DateTime> TERM_END_DATE { get; set; }
        public string TERM_SESSION { get; set; }
        public Nullable<System.DateTime> TERM_REG_END_DATE { get; set; }
        public Nullable<System.DateTime> TERM_PREREG_END_DATE { get; set; }
        public string TERM_REPORTING_TERM { get; set; }
        public Nullable<System.DateTime> TERM_ADD_START_DATE { get; set; }
        public Nullable<System.DateTime> TERM_ADD_END_DATE { get; set; }
        public Nullable<System.DateTime> TERM_DROP_GRADE_REQD_DATE { get; set; }
        public Nullable<System.DateTime> TERM_DROP_START_DATE { get; set; }
        public Nullable<System.DateTime> TERM_DROP_END_DATE { get; set; }
        public Nullable<System.DateTime> TERM_MEAL_START_DATE { get; set; }
        public Nullable<System.DateTime> TERM_MEAL_END_DATE { get; set; }
        public Nullable<System.DateTime> TERM_HOUSING_START_DATE { get; set; }
        public Nullable<System.DateTime> TERM_HOUSING_END_DATE { get; set; }
        public Nullable<System.DateTime> TERM_COMMENCEMENT_DATE { get; set; }
        public Nullable<decimal> TERM_SEQUENCE_NO { get; set; }
        public string TERM_CAMPUS_CALENDAR { get; set; }
        public string TERMS_ADDOPR { get; set; }
        public Nullable<System.DateTime> TERMS_ADDDATE { get; set; }
        public string TERMS_CHGOPR { get; set; }
        public Nullable<System.DateTime> TERMS_CHGDATE { get; set; }
        public string TERM_USER1 { get; set; }
        public string TERM_USER2 { get; set; }
        public string TERM_USER3 { get; set; }
        public string TERM_USER4 { get; set; }
        public string TERM_USER5 { get; set; }
        public string TERM_USER6 { get; set; }
        public string TERM_USER7 { get; set; }
        public string TERM_USER8 { get; set; }
        public string TERM_USER9 { get; set; }
        public string TERM_USER10 { get; set; }
        public string TERM_REG_PRIORITY_FLAG { get; set; }
        public Nullable<System.DateTime> TERM_BILL_START_DATE { get; set; }
        public Nullable<System.DateTime> TERM_BILL_END_DATE { get; set; }
        public string TERM_DEFAULT_ON_PLAN { get; set; }
        public string TERM_DEGREE_PLANNING { get; set; }
        public string TERM_PCF_PERIOD { get; set; }
        public string TERM_USE_IN_BEST_FIT_CALC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APPLICATION> APPLICATIONS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COURSE_SECTIONS> COURSE_SECTIONS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STUDENT_ACAD_CRED> STUDENT_ACAD_CRED { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STUDENT_ACAD_CRED> STUDENT_ACAD_CRED1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STUDENT_STANDINGS> STUDENT_STANDINGS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STUDENT_PROGRAMS> STUDENT_PROGRAMS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STUDENT_PROGRAMS> STUDENT_PROGRAMS1 { get; set; }
    }
}
