//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lcapas.Core.Models.Colldb
{
    using System;
    using System.Collections.Generic;
    
    public partial class VAL
    {
        public string VALCODE_ID { get; set; }
        public decimal POS { get; set; }
        public string VAL_MINIMUM_INPUT_STRING { get; set; }
        public string VAL_EXTERNAL_REPRESENTATION { get; set; }
        public string VAL_ACTION_CODE_1 { get; set; }
        public string VAL_INTERNAL_CODE { get; set; }
        public string VAL_ACTION_CODE_2 { get; set; }
        public string VAL_ACTION_CODE_3 { get; set; }
        public string VAL_ACTION_CODE_4 { get; set; }
    }
}
