//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lcapas.Core.Models.Lcappsdb
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcademicRecord
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AcademicRecord()
        {
            this.Courses = new HashSet<Course>();
            this.AcademicSessions = new HashSet<AcademicSession>();
            this.AcademicAwards = new HashSet<AcademicAward>();
        }
    
        public int AcademicRecordId { get; set; }
        public Nullable<Lcapas.Core.Library.Apas.CoreMain.StudentLevelCodeType> StudentLevel { get; set; }
        public Nullable<System.DateTime> FirstDateAttended { get; set; }
        public Nullable<System.DateTime> LastDateAttended { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDateTime { get; set; }
        public string ApplicationId { get; set; }
        public Nullable<int> School_InstitutionId { get; set; }
        public Nullable<int> Student_StudentId { get; set; }
        public Nullable<int> Response_ResponseId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Course> Courses { get; set; }
        public virtual Institution School { get; set; }
        public virtual Response Responses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AcademicSession> AcademicSessions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AcademicAward> AcademicAwards { get; set; }
        public virtual Student Student { get; set; }
    }
}
