//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lcapas.Core.Models.Lcappsdb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acknowledgement
    {
        public int AcknowledgementId { get; set; }
        public string Originator { get; set; }
        public string OriginatorAPASCode { get; set; }
        public bool IsSuccessful { get; set; }
        public string AcknowledgementValue { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDateTime { get; set; }
        public Nullable<int> TransmissionData_TransmissionDataId { get; set; }
    
        public virtual ApplicationMessage ApplicationMessage { get; set; }
        public virtual TransmissionData TransmissionData { get; set; }
    }
}
