//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lcapas.Core.Models.Lcappsdb
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationMessage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ApplicationMessage()
        {
            this.PayPalResponses = new HashSet<PayPalResponse>();
            this.Acknowledgements = new HashSet<Acknowledgement>();
        }
    
        public int ApplicationMessageId { get; set; }
        public string UUID { get; set; }
        public string DocumentID { get; set; }
        public string ApplicationID { get; set; }
        public string ApplicationBody { get; set; }
        public string SessionId { get; set; }
        public string SecurityToken { get; set; }
        public bool Valid { get; set; }
        public bool Production { get; set; }
        public bool Debugging { get; set; }
        public bool Administrator { get; set; }
        public string Username { get; set; }
        public Nullable<System.DateTime> ReceivedDateTime { get; set; }
        public Nullable<System.DateTime> DatashareDateTime { get; set; }
        public Nullable<System.DateTime> ParsedDateTime { get; set; }
        public Nullable<System.DateTime> SubmittedDateTime { get; set; }
        public Nullable<System.DateTime> PaidDateTime { get; set; }
        public Nullable<System.DateTime> ReturnedDateTime { get; set; }
        public Nullable<System.DateTime> CancelledDateTime { get; set; }
        public Nullable<System.DateTime> ExportedDateTime { get; set; }
        public Nullable<System.DateTime> DontExportDateTime { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDateTime { get; set; }
        public int SourceInstitutionId { get; set; }
        public int DestinationInstitution_InstitutionId { get; set; }
        public int StudentApplication_StudentApplicationId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PayPalResponse> PayPalResponses { get; set; }
        public virtual Institution SourceInstitution { get; set; }
        public virtual Institution DestinationInstitution { get; set; }
        public virtual StudentApplication StudentApplication { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acknowledgement> Acknowledgements { get; set; }
    }
}
