//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lcapas.Core.Models.Lcappsdb
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationProgram
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ApplicationProgram()
        {
            this.RequiresTranscript = true;
            this.ProgramDetails = new HashSet<ProgramDetail>();
        }
    
        public int ApplicationProgramId { get; set; }
        public string ProgramCode { get; set; }
        public string ProgramDesc { get; set; }
        public Nullable<int> ProgramOrder { get; set; }
        public bool Active { get; set; }
        public bool RequiresTranscript { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProgramDetail> ProgramDetails { get; set; }
    }
}
