//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lcapas.Core.Models.Lcappsdb
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ASN()
        {
            this.CollegeData = false;
        }
    
        public int ASNId { get; set; }
        public string AgencyAssignedID { get; set; }
        public Nullable<Lcapas.Core.Library.Apas.CoreMain.AgencyCodeType> AgencyCode { get; set; }
        public string AgencyName { get; set; }
        public Nullable<Lcapas.Core.Library.Apas.CoreMain.CountryCodeType> CountryCode { get; set; }
        public Nullable<Lcapas.Core.Library.Apas.CoreMain.StateProvinceCodeType> StateProvinceCode { get; set; }
        public bool CollegeData { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDateTime { get; set; }
        public int Student_StudentId { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
