//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lcapas.Core.Models.Lcappsdb
{
    using System;
    using System.Collections.Generic;
    
    public partial class BulkSendTranscript
    {
        public int BulkSendTranscriptId { get; set; }
        public string sNumber { get; set; }
        public Nullable<System.DateTime> SentDateTime { get; set; }
        public bool StudentRestriction { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDateTime { get; set; }
        public Nullable<int> Institution_InstitutionId { get; set; }
        public Nullable<int> Student_StudentId { get; set; }
    
        public virtual Institution Institution { get; set; }
        public virtual Student Student { get; set; }
    }
}
