//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lcapas.Core.Models.Lcappsdb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public int CourseId { get; set; }
        public string Title { get; set; }
        public string CourseNumber { get; set; }
        public string OriginalCourseID { get; set; }
        public string AgencyCourseID { get; set; }
        public string SectionNumber { get; set; }
        public Nullable<Lcapas.Core.Library.Apas.CoreMain.CourseLevelType> Level { get; set; }
        public Nullable<Lcapas.Core.Library.Apas.CoreMain.CourseCreditBasisType> CreditBasis { get; set; }
        public Nullable<Lcapas.Core.Library.Apas.CoreMain.CourseCreditUnitsType> CreditUnits { get; set; }
        public Nullable<Lcapas.Core.Library.Apas.CoreMain.CourseCreditLevelType> CreditLevel { get; set; }
        public string CreditValue { get; set; }
        public string CreditEarned { get; set; }
        public string AcademicGradeScaleCode { get; set; }
        public string AcademicGrade { get; set; }
        public Nullable<Lcapas.Core.Library.Apas.CoreMain.CourseAcademicGradeStatusCodeType> AcademicGradeStatusCode { get; set; }
        public string NarrativeExplanationGrade { get; set; }
        public Nullable<Lcapas.Core.Library.Apas.CoreMain.CourseRepeatCodeType> RepeatCode { get; set; }
        public string SubjectAbbreviation { get; set; }
        public string OverrideSchoolCourseNumber { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public Nullable<System.DateTime> DropDate { get; set; }
        public Nullable<System.DateTime> BeginDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<Lcapas.Core.Library.Apas.CoreMain.CourseApplicabilityType> Applicability { get; set; }
        public Nullable<Lcapas.Core.Library.Apas.CoreMain.CourseInstructionSiteType> InstructionSite { get; set; }
        public string InstructionSiteName { get; set; }
        public string QualityPointsEarned { get; set; }
        public Nullable<Lcapas.Core.Library.Apas.CoreMain.CourseGPAApplicabilityCodeType> GPAApplicabilityCode { get; set; }
        public string NoteMessage { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDateTime { get; set; }
        public int AcademicRecord_AcademicRecordId { get; set; }
        public Nullable<int> CourseOverrideSchool_InstitutionId { get; set; }
    
        public virtual AcademicRecord AcademicRecord { get; set; }
        public virtual Institution CourseOverrideSchool { get; set; }
    }
}
