//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lcapas.Core.Models.Lcappsdb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Immigration
    {
        public int ImmigrationId { get; set; }
        public System.DateTime FirstEntryIntoCountryDateTime { get; set; }
        public string NonImmigrantVisaNumber { get; set; }
        public Nullable<System.DateTime> VisaExpirationDateTime { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDateTime { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
