//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lcapas.Core.Models.Lcappsdb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class lcapasdb_entities : DbContext
    {
        public lcapasdb_entities()
            : base("name=lcapasdb_entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AcademicAward> AcademicAwards { get; set; }
        public virtual DbSet<AcademicRecord> AcademicRecords { get; set; }
        public virtual DbSet<AcademicSession> AcademicSessions { get; set; }
        public virtual DbSet<AccessGroup> AccessGroups { get; set; }
        public virtual DbSet<Acknowledgement> Acknowledgements { get; set; }
        public virtual DbSet<ActionType> ActionTypes { get; set; }
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<ApasCode> ApasCodes { get; set; }
        public virtual DbSet<ApasMessage> ApasMessages { get; set; }
        public virtual DbSet<ApplicationFee> ApplicationFees { get; set; }
        public virtual DbSet<ApplicationMessage> ApplicationMessages { get; set; }
        public virtual DbSet<ApplicationProgram> ApplicationPrograms { get; set; }
        public virtual DbSet<ASN> ASNs { get; set; }
        public virtual DbSet<BooleanValue> BooleanValues { get; set; }
        public virtual DbSet<CodeType> CodeTypes { get; set; }
        public virtual DbSet<ContactEmail> ContactEmails { get; set; }
        public virtual DbSet<ContactPerson> ContactPersons { get; set; }
        public virtual DbSet<ContactPhone> ContactPhones { get; set; }
        public virtual DbSet<ControllerType> ControllerTypes { get; set; }
        public virtual DbSet<Course> Courses { get; set; }
        public virtual DbSet<CourseTitle> CourseTitles { get; set; }
        public virtual DbSet<DateTimeValue> DateTimeValues { get; set; }
        public virtual DbSet<DoubleValue> DoubleValues { get; set; }
        public virtual DbSet<Email> Emails { get; set; }
        public virtual DbSet<ExceptionRecord> ExceptionRecords { get; set; }
        public virtual DbSet<InstitutionName> InstitutionNames { get; set; }
        public virtual DbSet<Institution> Institutions { get; set; }
        public virtual DbSet<IntegerValue> IntegerValues { get; set; }
        public virtual DbSet<KeyValueTempCache> KeyValueTempCaches { get; set; }
        public virtual DbSet<PayPalResponse> PayPalResponses { get; set; }
        public virtual DbSet<PermissionRecord> PermissionRecords { get; set; }
        public virtual DbSet<PersonName> PersonNames { get; set; }
        public virtual DbSet<Person> Persons { get; set; }
        public virtual DbSet<Phone> Phones { get; set; }
        public virtual DbSet<ProgramCampus> ProgramCampuses { get; set; }
        public virtual DbSet<ProgramDetail> ProgramDetails { get; set; }
        public virtual DbSet<ProgramTerm> ProgramTerms { get; set; }
        public virtual DbSet<ReceivedError> ReceivedErrors { get; set; }
        public virtual DbSet<Recipient> Recipients { get; set; }
        public virtual DbSet<ReferenceType> ReferenceTypes { get; set; }
        public virtual DbSet<Request> Requests { get; set; }
        public virtual DbSet<ResponseStatus> ResponseStatuses { get; set; }
        public virtual DbSet<ResponseHold> ResponseHolds { get; set; }
        public virtual DbSet<Response> Responses { get; set; }
        public virtual DbSet<SettingCategory> SettingCategories { get; set; }
        public virtual DbSet<Setting> Settings { get; set; }
        public virtual DbSet<ShortStringValue> ShortStringValues { get; set; }
        public virtual DbSet<Status> Statuses { get; set; }
        public virtual DbSet<StudentApplication> StudentApplications { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<SvcJob> SvcJobs { get; set; }
        public virtual DbSet<SvcLog> SvcLogs { get; set; }
        public virtual DbSet<SvcSched> SvcScheds { get; set; }
        public virtual DbSet<TranscriptHold> TranscriptHolds { get; set; }
        public virtual DbSet<Transcript> Transcripts { get; set; }
        public virtual DbSet<TransmissionData> TransmissionDatas { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<ValCodeLookup> ValCodeLookups { get; set; }
        public virtual DbSet<ValCode> ValCodes { get; set; }
        public virtual DbSet<Citizenship> Citizenships { get; set; }
        public virtual DbSet<Residency> Residencies { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<Disability> Disabilities { get; set; }
        public virtual DbSet<Immigration> Immigrations { get; set; }
        public virtual DbSet<TranscriptJob> TranscriptJobs { get; set; }
        public virtual DbSet<RequestorReceiver> RequestorReceivers { get; set; }
        public virtual DbSet<NoteMessage> NoteMessages { get; set; }
        public virtual DbSet<TransactionTranscript> TransactionTranscripts { get; set; }
        public virtual DbSet<TransactionRequestLog> TransactionRequestLogs { get; set; }
        public virtual DbSet<TransactionCourse> TransactionCourses { get; set; }
        public virtual DbSet<sNumber> sNumbers { get; set; }
        public virtual DbSet<StudentAlias> StudentAlias { get; set; }
        public virtual DbSet<TranscriptRestriction> TranscriptRestrictions { get; set; }
        public virtual DbSet<History> Histories { get; set; }
        public virtual DbSet<TranscriptTermDesc> TranscriptTermDescs { get; set; }
        public virtual DbSet<AdmissionOutstandingRequest> AdmissionOutstandingRequests { get; set; }
        public virtual DbSet<RecordsOutstandingRequest> RecordsOutstandingRequests { get; set; }
        public virtual DbSet<RecordsHoldRespons> RecordsHoldResponses { get; set; }
        public virtual DbSet<AdmissionOfflineSearchRespons> AdmissionOfflineSearchResponses { get; set; }
        public virtual DbSet<Requests_Alberta_Education> Requests_Alberta_Education { get; set; }
        public virtual DbSet<BulkSendTranscript> BulkSendTranscripts { get; set; }
        public virtual DbSet<SentEmail> SentEmails { get; set; }
        public virtual DbSet<ReportQuery> ReportQueries { get; set; }
        public virtual DbSet<MyCredsMessage> MyCredsMessages { get; set; }
    }
}
