//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lcapas.Core.Models.Lcappsdb
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyCredsMessage
    {
        public int MessageId { get; set; }
        public string UUID { get; set; }
        public string sNumber { get; set; }
        public Lcapas.Core.Library.Enums.MyCredsDocumentTypes MessageType { get; set; }
        public string MessageXML { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDateTime { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string BatchCode { get; set; }
    }
}
