//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lcapas.Core.Models.Lcappsdb
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayPalResponse
    {
        public int PayPalResponseId { get; set; }
        public string UUID { get; set; }
        public string SECURETOKEN { get; set; }
        public string AUTHCODE { get; set; }
        public string PNREF { get; set; }
        public string RESPMSG { get; set; }
        public string RESULT { get; set; }
        public string BILLTOLASTNAME { get; set; }
        public string BILLTOFIRSTNAME { get; set; }
        public string BILLTOEMAIL { get; set; }
        public string BILLTOSTREET { get; set; }
        public string BILLTOCOUNTRY { get; set; }
        public string BILLTOZIP { get; set; }
        public string BILLTOPHONE { get; set; }
        public Lcapas.Core.Library.Enums.PayPalCardType CARDTYPE { get; set; }
        public Lcapas.Core.Library.Enums.PaymentMethodType METHOD { get; set; }
        public string ACCT { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDateTime { get; set; }
        public int ApplicationMessage_ApplicationMessageId { get; set; }
    
        public virtual ApplicationMessage ApplicationMessage { get; set; }
    }
}
