//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lcapas.Core.Models.Lcappsdb
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgramDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProgramDetail()
        {
            this.StudentApplications = new HashSet<StudentApplication>();
        }
    
        public int ProgramDetailsId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public bool MonthlyBased { get; set; }
        public Nullable<int> ProgramDetailOrder { get; set; }
        public bool Active { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDateTime { get; set; }
        public Nullable<int> ProgramTerm_ProgramTermId { get; set; }
        public Nullable<int> ProgramCampus_ProgramCampusId { get; set; }
        public Nullable<int> ApplicationProgram_ApplicationProgramId { get; set; }
    
        public virtual ApplicationProgram ApplicationProgram { get; set; }
        public virtual ProgramCampus ProgramCampus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentApplication> StudentApplications { get; set; }
        public virtual ProgramTerm ProgramTerm { get; set; }
    }
}
