//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lcapas.Core.Models.Lcappsdb
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceivedError
    {
        public int ReceivedErrorId { get; set; }
        public string UUID { get; set; }
        public string RequestTrackingID { get; set; }
        public string OriginalMessageType { get; set; }
        public string OriginalMessageBody { get; set; }
        public string ErrorMessage { get; set; }
        public Nullable<System.DateTime> ReceivedDateTime { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDateTime { get; set; }
    }
}
