//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lcapas.Core.Models.Lcappsdb
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentApplication
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StudentApplication()
        {
            this.ApplicationMessages = new HashSet<ApplicationMessage>();
        }
    
        public int StudentApplicationId { get; set; }
        public string ApplicationID { get; set; }
        public string ApplicationSource { get; set; }
        public string SessionDesignator { get; set; }
        public Nullable<bool> PreviouslyApplied { get; set; }
        public Nullable<int> StartingYear { get; set; }
        public string StudyLoad { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDateTime { get; set; }
        public Nullable<int> Student_StudentId { get; set; }
        public Nullable<int> ApplicationFee_ApplicationFeeId { get; set; }
        public Nullable<int> ReferenceType_ReferenceTypeId { get; set; }
        public Nullable<int> ProgramDetail_ProgramDetailsId { get; set; }
    
        public virtual ApplicationFee ApplicationFee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApplicationMessage> ApplicationMessages { get; set; }
        public virtual ProgramDetail ProgramDetail { get; set; }
        public virtual ReferenceType ReferenceType { get; set; }
        public virtual Student Student { get; set; }
    }
}
