//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lcapas.Core.Models.Lcappsdb
{
    using System;
    using System.Collections.Generic;
    
    public partial class SvcLog
    {
        public int SvcLogId { get; set; }
        public System.DateTime SvcStartDateTime { get; set; }
        public System.DateTime SvcEndDateTime { get; set; }
        public bool SvcFail { get; set; }
        public string SvcFailMsg { get; set; }
        public int SvcJob_SvcJobId { get; set; }
    
        public virtual SvcJob SvcJob { get; set; }
    }
}
