//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lcapas.Core.Models.Lcappsdb
{
    using System;
    using System.Collections.Generic;
    
    public partial class TranscriptHold
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TranscriptHold()
        {
            this.CourseTitles = new HashSet<CourseTitle>();
        }
    
        public int TranscriptHoldID { get; set; }
        public Nullable<Lcapas.Core.Library.Apas.AcademicRecord.HoldTypeType> HoldType { get; set; }
        public string HoldTypeData { get; set; }
        public string SessionDesignator { get; set; }
        public string SessionName { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDateTime { get; set; }
        public Nullable<int> Recipient_RecipientId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CourseTitle> CourseTitles { get; set; }
        public virtual Recipient Recipient { get; set; }
    }
}
