//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lcapas.Core.Models.Lcappsdb
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransmissionData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TransmissionData()
        {
            this.Requests = new HashSet<Request>();
            this.Responses = new HashSet<Response>();
            this.Statuses = new HashSet<Status>();
            this.Transcripts = new HashSet<Transcript>();
            this.NoteMessages = new HashSet<NoteMessage>();
            this.Acknowledgements = new HashSet<Acknowledgement>();
        }
    
        public int TransmissionDataId { get; set; }
        public string Uuid { get; set; }
        public string DocumentID { get; set; }
        public string Xml { get; set; }
        public Nullable<Lcapas.Core.Library.Apas.CoreMain.DocumentTypeCodeType> DocumentTypeCode { get; set; }
        public Nullable<Lcapas.Core.Library.Apas.CoreMain.TransmissionTypeType> TransmissionTypeType { get; set; }
        public Nullable<Lcapas.Core.Library.Apas.CoreMain.DocumentProcessCodeType> DocumentProcessCodeType { get; set; }
        public Nullable<Lcapas.Core.Library.Apas.CoreMain.DocumentOfficialCodeType> DocumentOfficialCodeType { get; set; }
        public Nullable<Lcapas.Core.Library.Apas.CoreMain.DocumentCompleteCodeType> DocumentCompleteCodeType { get; set; }
        public string RequestTrackingID { get; set; }
        public Nullable<System.DateTime> ExportedDateTime { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDateTime { get; set; }
        public int SourceInstitution_InstitutionId { get; set; }
        public int DestinationInstitution_InstitutionId { get; set; }
    
        public virtual Institution DestinationInstitution { get; set; }
        public virtual Institution SourceInstitution { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Request> Requests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Response> Responses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Status> Statuses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transcript> Transcripts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NoteMessage> NoteMessages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acknowledgement> Acknowledgements { get; set; }
    }
}
