//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lcapas.Core.Models.Lcappsdb
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionRequestLog
    {
        public int TransactionRequestLogId { get; set; }
        public string TransactionRequestLogUuid { get; set; }
        public string StudentId { get; set; }
        public string RequestType { get; set; }
        public string RecipientId { get; set; }
        public string RecipientName { get; set; }
        public string RecipientAddressLines { get; set; }
        public string RecipientCity { get; set; }
        public string RecipientState { get; set; }
        public string RecipientPostalCode { get; set; }
        public string RecipientCountryCode { get; set; }
        public string NumberOfCopies { get; set; }
        public string Comments { get; set; }
        public string RequestHoldCode { get; set; }
        public string TranscriptGrouping { get; set; }
        public string ErrorOccured { get; set; }
        public string ErrorMessage { get; set; }
        public string StudentRequestLogsId { get; set; }
        public Nullable<System.DateTime> CompletedDateTime { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public Nullable<System.DateTime> ModifiedDateTime { get; set; }
    }
}
