//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lcapas.Core.Models.Lcappsdb
{
    using System;
    using System.Collections.Generic;
    
    public partial class TranscriptRestriction
    {
        public int TranscriptRestrictionId { get; set; }
        public string TranscriptRestrictionCode { get; set; }
        public string TranscriptRestrictionDesc { get; set; }
        public Nullable<bool> IsRule { get; set; }
        public Nullable<bool> Active { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDateTime { get; set; }
    }
}
