//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lcapas.Core.Models.Lcappsdb
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionCourse
    {
        public int TransactionCourseId { get; set; }
        public string AExternalTranscriptsId { get; set; }
        public string AExtlPersonId { get; set; }
        public string AExtlInstitution { get; set; }
        public string AExtlCourse { get; set; }
        public string AExtlTitle { get; set; }
        public string AExtlCred { get; set; }
        public string AExtlGrade { get; set; }
        public string AExtlGradeScheme { get; set; }
        public string AExtlStartDate { get; set; }
        public string AExtlEndDate { get; set; }
        public string AExtlOpr { get; set; }
        public string AExtlPersInstIdx { get; set; }
        public string Result { get; set; }
        public Nullable<System.DateTime> CompletedDateTime { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public Nullable<System.DateTime> ModifiedDateTime { get; set; }
    }
}
