GO
/****** Object:  StoredProcedure [dbo].[usp_get_stu_grades]    Script Date: 12/1/2016 8:13:23 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- Author:		<Patrick Dudley>
-- Create date: <22 Nov 2012>
-- Description:	<Get student grades for transcripts>
-- =============================================
ALTER PROCEDURE [dbo].[usp_get_stu_grades]
	@strStudentID varchar(7),
	@strAcadLevel varchar(3)
	
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

    -- Insert statements for procedure here
	SELECT DISTINCT GRP.STC_PERSON_ID AS STU_ID
		, REPLACE(GRP.STC_COURSE_NAME,'-','') AS CRS_CODE
		, ISNULL(GRP.STC_TERM, 'TR') AS CRS_TERM
		, GRP.STC_TITLE AS CRS_TITLE
		, CAST(GRP.STC_CRED AS DECIMAL(4,2)) AS CRS_ATT_CRD
		, CAST(GRP.STC_CMPL_CRED AS DECIMAL(4,2)) AS CRS_CMPL_CRD
		, CAST(GRP.STC_GPA_CRED AS DECIMAL(4,2)) AS CRS_GPA_CRD
		, GS.GRD_GRADE AS CRS_GRADE
		, CAST(GRP.STC_GRADE_PTS AS DECIMAL(4,2)) AS CRS_GRDPT
		, CAST(ISNULL(SUM(GRP.STC_CMPL_CRED) over(partition by GRP.STC_TERM, GRP.STC_PERSON_ID),0.00) AS DECIMAL(4,2)) AS TRM_CRD
		, SST.STS_ACAD_STANDING AS LC_STU_TRM_STAND
		, CAST(ROUND((CAST(ISNULL(SUM(GRP.STC_GRADE_PTS) over(partition by GRP.STC_TERM, GRP.STC_PERSON_ID),0.00) AS DECIMAL(4,2)) / NULLIF(CAST(ISNULL(SUM(GRP.STC_GPA_CRED) over(partition by GRP.STC_TERM, GRP.STC_PERSON_ID),0.00) AS DECIMAL(4,2)),0.00)),3,1) AS DECIMAL(4,2)) AS TRM_GPA
		, GRP.STC_END_DATE AS CRS_END_DATE
		, GRP.STC_ACAD_LEVEL AS CRS_ACAD_LEVEL
	FROM (SELECT STC_TERM,SUBSTRING(STC_PERSON_ID,0,8) AS STC_PERSON_ID, STC_CMPL_CRED, STC_ATT_CRED, STUDENT_ACAD_CRED.STC_GPA_CRED, STUDENT_ACAD_CRED.STC_GRADE_PTS,STC_END_DATE, STC_VERIFIED_GRADE, STUDENT_ACAD_CRED_ID, STC_SECTION_NO, STC_COURSE_NAME, STC_TITLE, STC_CRED, STC_ACAD_LEVEL
		FROM [dbo].[STUDENT_ACAD_CRED]
		WHERE SUBSTRING(STC_PERSON_ID,0,8) = @strStudentID
		AND STC_ACAD_LEVEL = @strAcadLevel) GRP
	LEFT JOIN [dbo].[STUDENT_STANDINGS] SST
		ON RTRIM(SST.STS_STUDENT) = GRP.STC_PERSON_ID
		AND SST.STS_TYPE = 'TERM'
		AND SST.STS_TERM = GRP.STC_TERM
	LEFT JOIN GRADES GS
		ON GS.GRADES_ID = GRP.STC_VERIFIED_GRADE
	LEFT JOIN [dbo].[STC_STATUSES] STAT 
		ON GRP.STUDENT_ACAD_CRED_ID = STAT.STUDENT_ACAD_CRED_ID
		AND STAT.POS='1'
	ORDER BY GRP.STC_END_DATE ASC
END

