//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lcapas.Core.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://applyalberta.ca/APAS.WebServices/DistributedSessionService.asmx")]
        public string LcapasCore_distsesssvc_DistributedSessionService {
            get {
                return ((string)(this["LcapasCore_distsesssvc_DistributedSessionService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://applyalberta.ca/APAS.WebServices/InstitutionInformationAndCodesServices.a" +
            "smx")]
        public string LcapasCore_instsvc_InstitutionInformationAndCodesServices {
            get {
                return ((string)(this["LcapasCore_instsvc_InstitutionInformationAndCodesServices"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://apasp.lethbridgecollege.ab.ca/apasproxyinternal/APASQueueService.asmx")]
        public string LcapasCore_quesvc_APASQueueService {
            get {
                return ((string)(this["LcapasCore_quesvc_APASQueueService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://apasp.lethbridgecollege.ab.ca/APASProxyInternal/APASQueueServiceExt2.asmx" +
            "")]
        public string LcapasCore_quesvcext2_APASQueueServiceExt2 {
            get {
                return ((string)(this["LcapasCore_quesvcext2_APASQueueServiceExt2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://applyalberta.ca/APAS.WebServices/RefreshTokenServices.asmx")]
        public string LcapasCore_reftokensvc_RefreshTokenServices {
            get {
                return ((string)(this["LcapasCore_reftokensvc_RefreshTokenServices"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://applyalberta.ca/APAS.WebServices/InstitutionInformationAndCodesServices.a" +
            "smx")]
        public string LcapasCore_devinstsvc_InstitutionInformationAndCodesServices {
            get {
                return ((string)(this["LcapasCore_devinstsvc_InstitutionInformationAndCodesServices"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://apasp.lethbridgecollege.ab.ca/apasproxyinternal/APASQueueService.asmx")]
        public string LcapasCore_devquesvc_APASQueueService {
            get {
                return ((string)(this["LcapasCore_devquesvc_APASQueueService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://apasp.lethbridgecollege.ab.ca/APASProxyInternal/APASQueueServiceExt2.asmx")]
        public string LcapasCore_devquesvc2_APASQueueServiceExt2 {
            get {
                return ((string)(this["LcapasCore_devquesvc2_APASQueueServiceExt2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://applyalberta.ca/APAS.WebServices/RefreshTokenServices.asmx")]
        public string LcapasCore_devtoksvc_RefreshTokenServices {
            get {
                return ((string)(this["LcapasCore_devtoksvc_RefreshTokenServices"]));
            }
        }
    }
}
