//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Lcapas.Core.instsvc {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="InstitutionInformationAndCodesServicesSoap", Namespace="http://applyalberta.ca/")]
    public partial class InstitutionInformationAndCodesServices : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetInstitutionByAPASCodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetInstitutionListOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public InstitutionInformationAndCodesServices() {
            this.Url = global::Lcapas.Core.Properties.Settings.Default.LcapasCore_instsvc_InstitutionInformationAndCodesServices;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetInstitutionByAPASCodeCompletedEventHandler GetInstitutionByAPASCodeCompleted;
        
        /// <remarks/>
        public event GetInstitutionListCompletedEventHandler GetInstitutionListCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://applyalberta.ca/GetInstitutionByAPASCode", RequestNamespace="http://applyalberta.ca/", ResponseNamespace="http://applyalberta.ca/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public InstitutionDetails GetInstitutionByAPASCode(string code) {
            object[] results = this.Invoke("GetInstitutionByAPASCode", new object[] {
                        code});
            return ((InstitutionDetails)(results[0]));
        }
        
        /// <remarks/>
        public void GetInstitutionByAPASCodeAsync(string code) {
            this.GetInstitutionByAPASCodeAsync(code, null);
        }
        
        /// <remarks/>
        public void GetInstitutionByAPASCodeAsync(string code, object userState) {
            if ((this.GetInstitutionByAPASCodeOperationCompleted == null)) {
                this.GetInstitutionByAPASCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetInstitutionByAPASCodeOperationCompleted);
            }
            this.InvokeAsync("GetInstitutionByAPASCode", new object[] {
                        code}, this.GetInstitutionByAPASCodeOperationCompleted, userState);
        }
        
        private void OnGetInstitutionByAPASCodeOperationCompleted(object arg) {
            if ((this.GetInstitutionByAPASCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetInstitutionByAPASCodeCompleted(this, new GetInstitutionByAPASCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://applyalberta.ca/GetInstitutionList", RequestNamespace="http://applyalberta.ca/", ResponseNamespace="http://applyalberta.ca/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public InstitutionList GetInstitutionList(InstitutionListFilterCriteria filter) {
            object[] results = this.Invoke("GetInstitutionList", new object[] {
                        filter});
            return ((InstitutionList)(results[0]));
        }
        
        /// <remarks/>
        public void GetInstitutionListAsync(InstitutionListFilterCriteria filter) {
            this.GetInstitutionListAsync(filter, null);
        }
        
        /// <remarks/>
        public void GetInstitutionListAsync(InstitutionListFilterCriteria filter, object userState) {
            if ((this.GetInstitutionListOperationCompleted == null)) {
                this.GetInstitutionListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetInstitutionListOperationCompleted);
            }
            this.InvokeAsync("GetInstitutionList", new object[] {
                        filter}, this.GetInstitutionListOperationCompleted, userState);
        }
        
        private void OnGetInstitutionListOperationCompleted(object arg) {
            if ((this.GetInstitutionListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetInstitutionListCompleted(this, new GetInstitutionListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://applyalberta.ca/")]
    public partial class InstitutionDetails {
        
        private string aCTField;
        
        private string aPASField;
        
        private string aTPField;
        
        private string cCDField;
        
        private string cEEBACTField;
        
        private string cSISField;
        
        private string dUNSField;
        
        private string eSISField;
        
        private string fICEField;
        
        private string iPEDSField;
        
        private string nCHELPIDField;
        
        private string oPEIDField;
        
        private string pSISField;
        
        private string uSISField;
        
        private string organizationNameField;
        
        private string organizationIDCodeField;
        
        private string countryNameField;
        
        private string provinceNameField;
        
        private string municipalityNameField;
        
        private string postalCodeField;
        
        private string[] institutionTypesField;
        
        private string[] roleTypeCodesField;
        
        private string addressLine1Field;
        
        private string addressLine2Field;
        
        private string addressLine3Field;
        
        private string electronicAddressField;
        
        private string faxNumberField;
        
        private string phoneNumberField;
        
        private string webSiteURLField;
        
        private bool isApplicationServiceProviderField;
        
        private bool isTranscriptPublisherField;
        
        private bool isTranscriptSubscriberField;
        
        private string parentAPASCodeField;
        
        private string institutionStatusField;
        
        /// <remarks/>
        public string ACT {
            get {
                return this.aCTField;
            }
            set {
                this.aCTField = value;
            }
        }
        
        /// <remarks/>
        public string APAS {
            get {
                return this.aPASField;
            }
            set {
                this.aPASField = value;
            }
        }
        
        /// <remarks/>
        public string ATP {
            get {
                return this.aTPField;
            }
            set {
                this.aTPField = value;
            }
        }
        
        /// <remarks/>
        public string CCD {
            get {
                return this.cCDField;
            }
            set {
                this.cCDField = value;
            }
        }
        
        /// <remarks/>
        public string CEEBACT {
            get {
                return this.cEEBACTField;
            }
            set {
                this.cEEBACTField = value;
            }
        }
        
        /// <remarks/>
        public string CSIS {
            get {
                return this.cSISField;
            }
            set {
                this.cSISField = value;
            }
        }
        
        /// <remarks/>
        public string DUNS {
            get {
                return this.dUNSField;
            }
            set {
                this.dUNSField = value;
            }
        }
        
        /// <remarks/>
        public string ESIS {
            get {
                return this.eSISField;
            }
            set {
                this.eSISField = value;
            }
        }
        
        /// <remarks/>
        public string FICE {
            get {
                return this.fICEField;
            }
            set {
                this.fICEField = value;
            }
        }
        
        /// <remarks/>
        public string IPEDS {
            get {
                return this.iPEDSField;
            }
            set {
                this.iPEDSField = value;
            }
        }
        
        /// <remarks/>
        public string NCHELPID {
            get {
                return this.nCHELPIDField;
            }
            set {
                this.nCHELPIDField = value;
            }
        }
        
        /// <remarks/>
        public string OPEID {
            get {
                return this.oPEIDField;
            }
            set {
                this.oPEIDField = value;
            }
        }
        
        /// <remarks/>
        public string PSIS {
            get {
                return this.pSISField;
            }
            set {
                this.pSISField = value;
            }
        }
        
        /// <remarks/>
        public string USIS {
            get {
                return this.uSISField;
            }
            set {
                this.uSISField = value;
            }
        }
        
        /// <remarks/>
        public string OrganizationName {
            get {
                return this.organizationNameField;
            }
            set {
                this.organizationNameField = value;
            }
        }
        
        /// <remarks/>
        public string OrganizationIDCode {
            get {
                return this.organizationIDCodeField;
            }
            set {
                this.organizationIDCodeField = value;
            }
        }
        
        /// <remarks/>
        public string CountryName {
            get {
                return this.countryNameField;
            }
            set {
                this.countryNameField = value;
            }
        }
        
        /// <remarks/>
        public string ProvinceName {
            get {
                return this.provinceNameField;
            }
            set {
                this.provinceNameField = value;
            }
        }
        
        /// <remarks/>
        public string MunicipalityName {
            get {
                return this.municipalityNameField;
            }
            set {
                this.municipalityNameField = value;
            }
        }
        
        /// <remarks/>
        public string PostalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
            }
        }
        
        /// <remarks/>
        public string[] InstitutionTypes {
            get {
                return this.institutionTypesField;
            }
            set {
                this.institutionTypesField = value;
            }
        }
        
        /// <remarks/>
        public string[] RoleTypeCodes {
            get {
                return this.roleTypeCodesField;
            }
            set {
                this.roleTypeCodesField = value;
            }
        }
        
        /// <remarks/>
        public string AddressLine1 {
            get {
                return this.addressLine1Field;
            }
            set {
                this.addressLine1Field = value;
            }
        }
        
        /// <remarks/>
        public string AddressLine2 {
            get {
                return this.addressLine2Field;
            }
            set {
                this.addressLine2Field = value;
            }
        }
        
        /// <remarks/>
        public string AddressLine3 {
            get {
                return this.addressLine3Field;
            }
            set {
                this.addressLine3Field = value;
            }
        }
        
        /// <remarks/>
        public string ElectronicAddress {
            get {
                return this.electronicAddressField;
            }
            set {
                this.electronicAddressField = value;
            }
        }
        
        /// <remarks/>
        public string FaxNumber {
            get {
                return this.faxNumberField;
            }
            set {
                this.faxNumberField = value;
            }
        }
        
        /// <remarks/>
        public string PhoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                this.phoneNumberField = value;
            }
        }
        
        /// <remarks/>
        public string WebSiteURL {
            get {
                return this.webSiteURLField;
            }
            set {
                this.webSiteURLField = value;
            }
        }
        
        /// <remarks/>
        public bool IsApplicationServiceProvider {
            get {
                return this.isApplicationServiceProviderField;
            }
            set {
                this.isApplicationServiceProviderField = value;
            }
        }
        
        /// <remarks/>
        public bool IsTranscriptPublisher {
            get {
                return this.isTranscriptPublisherField;
            }
            set {
                this.isTranscriptPublisherField = value;
            }
        }
        
        /// <remarks/>
        public bool IsTranscriptSubscriber {
            get {
                return this.isTranscriptSubscriberField;
            }
            set {
                this.isTranscriptSubscriberField = value;
            }
        }
        
        /// <remarks/>
        public string ParentAPASCode {
            get {
                return this.parentAPASCodeField;
            }
            set {
                this.parentAPASCodeField = value;
            }
        }
        
        /// <remarks/>
        public string InstitutionStatus {
            get {
                return this.institutionStatusField;
            }
            set {
                this.institutionStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://applyalberta.ca/")]
    public partial class InstitutionListItem {
        
        private string organizationNameField;
        
        private string aPASCodeField;
        
        /// <remarks/>
        public string OrganizationName {
            get {
                return this.organizationNameField;
            }
            set {
                this.organizationNameField = value;
            }
        }
        
        /// <remarks/>
        public string APASCode {
            get {
                return this.aPASCodeField;
            }
            set {
                this.aPASCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://applyalberta.ca/")]
    public partial class InstitutionList {
        
        private int numberOfRecordsFoundField;
        
        private int offsetField;
        
        private InstitutionListItem[] resultField;
        
        /// <remarks/>
        public int NumberOfRecordsFound {
            get {
                return this.numberOfRecordsFoundField;
            }
            set {
                this.numberOfRecordsFoundField = value;
            }
        }
        
        /// <remarks/>
        public int Offset {
            get {
                return this.offsetField;
            }
            set {
                this.offsetField = value;
            }
        }
        
        /// <remarks/>
        public InstitutionListItem[] Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://applyalberta.ca/")]
    public partial class InstitutionListFilterCriteria {
        
        private string institutionTypeField;
        
        private System.DateTime updateDateField;
        
        private int recordOffsetField;
        
        private string countryField;
        
        private string regionField;
        
        private string cityField;
        
        private string nameField;
        
        private int maxResultsField;
        
        private string aPASCodeField;
        
        private string isTranscriptSubscriberField;
        
        private string isTranscriptPublisherField;
        
        private string isApplicationProviderField;
        
        /// <remarks/>
        public string InstitutionType {
            get {
                return this.institutionTypeField;
            }
            set {
                this.institutionTypeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime UpdateDate {
            get {
                return this.updateDateField;
            }
            set {
                this.updateDateField = value;
            }
        }
        
        /// <remarks/>
        public int RecordOffset {
            get {
                return this.recordOffsetField;
            }
            set {
                this.recordOffsetField = value;
            }
        }
        
        /// <remarks/>
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        public string Region {
            get {
                return this.regionField;
            }
            set {
                this.regionField = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public int MaxResults {
            get {
                return this.maxResultsField;
            }
            set {
                this.maxResultsField = value;
            }
        }
        
        /// <remarks/>
        public string APASCode {
            get {
                return this.aPASCodeField;
            }
            set {
                this.aPASCodeField = value;
            }
        }
        
        /// <remarks/>
        public string IsTranscriptSubscriber {
            get {
                return this.isTranscriptSubscriberField;
            }
            set {
                this.isTranscriptSubscriberField = value;
            }
        }
        
        /// <remarks/>
        public string IsTranscriptPublisher {
            get {
                return this.isTranscriptPublisherField;
            }
            set {
                this.isTranscriptPublisherField = value;
            }
        }
        
        /// <remarks/>
        public string IsApplicationProvider {
            get {
                return this.isApplicationProviderField;
            }
            set {
                this.isApplicationProviderField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetInstitutionByAPASCodeCompletedEventHandler(object sender, GetInstitutionByAPASCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetInstitutionByAPASCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetInstitutionByAPASCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public InstitutionDetails Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((InstitutionDetails)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetInstitutionListCompletedEventHandler(object sender, GetInstitutionListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetInstitutionListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetInstitutionListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public InstitutionList Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((InstitutionList)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591